
-- Consulta Filais
SELECT DISTINCT SUBSTRING (M0_CODFIL,1,2) FROM SYS_COMPANY

--Acesso usuários por Filiais
Select FILIAL.USR_ID, USR.USR_CODIGO, USR.USR_ID, USR.USR_EMAIL, USR.USR_MSBLQL, * From SYS_USR_FILIAL FILIAL

	Inner Join SYS_USR USR With(Nolock)
	ON USR.USR_ID = FILIAL.USR_ID
	And USR.D_E_L_E_T_=''
	
Where FILIAL.USR_ID = '000663' and FILIAL.USR_ACESSO = 'T' and FILIAL.D_E_L_E_T_=''