DECLARE @CFILDE VARCHAR(4)																																	
DECLARE @CFILATE VARCHAR(4)
DECLARE @CBASEDE VARCHAR(10)																																	
DECLARE @CBASEATE VARCHAR(10)
DECLARE @CITEMDE VARCHAR(4)																																	
DECLARE @CITEMATE VARCHAR(4)
DECLARE @DDATADE VARCHAR(10)																																	
DECLARE @DDATAATE VARCHAR(10)
DECLARE @DDATAANT VARCHAR(10)
DECLARE @DDATABX  VARCHAR(10)
 
SET @CFILDE   = 'AA01' 
SET @CFILATE  = 'ZZ01' 
SET @CBASEDE  = ''
SET @CBASEATE = 'ZZZZZZZZZZ'
SET @CITEMDE  = ''
SET @CITEMATE = 'ZZZZ'
SET @DDATADE  = '20220101'
SET @DDATAATE = '20221028'
 

			
EXEC MAPAATIVO_01 @CFILDE,@CFILATE,@CBASEDE,@CBASEATE,@CITEMDE,@CITEMATE,@DDATADE,@DDATAATE
 