-- Script para Usuarios, Permissoes e Acessos PIMS

SELECT DISTINCT U.USER_ID, U.USER_NAME, SUBSTRING (UN.DE_UNI_ADM,1,4), GR.GROUP_NAME NOME_GRUPO , AC.MENU_NAME ROTINA, AC.PERMISSIONS PERMISSOES  FROM PRXUSER U

INNER JOIN PRXUSER_UNIDADEADM X ON X.USER_ID=U.USER_ID

INNER JOIN UNIDADEADM UN ON UN.ID_UNIDADEADM=X.ID_UNIDADEADM

INNER JOIN PRXUSER_GROUPS G ON G.USER_ID=U.USER_ID

INNER JOIN PRXGROUP GR ON GR.GROUP_ID=G.GROUP_ID

INNER JOIN PRXMENU_GROUP AC ON AC.GROUP_ID= GR.GROUP_ID AND AC.GROUP_ID=G.GROUP_ID

--WHERE U.USER_ID='aiyra.trindade'

ORDER BY 1,3,4,5