
--Grupos de Acessos
Select * From SYS_GRP_ACCESS

--Tabela UserxAcessos 
Select * From SYS_USR_ACCESS
Where USR_ID = '000401'

-- Tabela Usuários 
Select * From SYS_USR
Where USR_CODIGO Like 'suel%'

Select * From SYS_RULES_FEATURES

--Relatorio Acesso User
Select Distinct SYS_USR.USR_ID, SYS_USR.USR_NOME, GRP_ACCCESS.GR__CODACESSO, GRP_ACCCESS.GR__DESCACESSO,
USR_ACCESS.USR_ACESSO,

   CASE
       WHEN USR_ACCESS.USR_ACESSO = 'T' THEN 'Permitido'
       WHEN USR_ACCESS.USR_ACESSO = 'F' THEN 'Não Permitido'
       ELSE '*'
   END Acesso

From SYS_USR_ACCESS USR_ACCESS

	Inner Join SYS_GRP_ACCESS GRP_ACCCESS  WITH (NOLOCK)
	ON GRP_ACCCESS.GR__CODACESSO = USR_ACCESS.USR_CODACESSO
	AND GRP_ACCCESS.D_E_L_E_T_ =''

	Inner Join SYS_USR SYS_USR WITH (NOLOCK)
	ON SYS_USR.USR_ID = USR_ACCESS.USR_ID
	AND SYS_USR.D_E_L_E_T_ =''
			
Where USR_ACCESS.USR_ID Between '000783' and '000783' And SYS_USR.USR_MSBLQL ='2'
--Order By USR_ACCESS.USR_ID, GR__CODACESSO




--Relatório 
DECLARE @CUSRDE AS CHAR(06), @CUSRATE AS CHAR(06), @CROTDE AS CHAR(15),@CROTATE AS CHAR(15)
SET @CUSRDE = '000783'
SET @CUSRATE = '000783'
SET @CROTDE = ''
SET @CROTATE = 'zzzzzzzz'

SELECT DISTINCT *
FROM
  (SELECT U.USR_ID Codigo,
          USR_CODIGO Login,
          USR_NOME Nome,
          F_FUNCTION Rotina,
          IsNull(right(replicate('0',2) + convert(VARCHAR,RL__ITEM),2), '00') Item,
          IsNull(RL__DESMDEF, 'Todos') Descricao,
          CASE
              WHEN RL__ACESSO = '1' THEN 'Permitido'
              WHEN RL__ACESSO = '2' THEN 'Não Permitido'
              WHEN RL__ACESSO = '3' THEN 'Negado'
              ELSE '*'
          END Acesso
   FROM SYS_USR U
   INNER JOIN SYS_USR_MODULE M ON M.USR_ID=U.USR_ID
   AND M.USR_ACESSO='T'
   AND M.D_E_L_E_T_=' '
   LEFT JOIN MPMENU_MENU MENU ON MENU.M_ID = M.USR_ARQMENU
   AND MENU.D_E_L_E_T_=' '
   LEFT JOIN MPMENU_ITEM ITEM ON MENU.M_ID = ITEM.I_ID_MENU
   AND ITEM.D_E_L_E_T_=' '
   LEFT JOIN MPMENU_FUNCTION FUNC ON FUNC.F_ID = ITEM.I_ID_FUNC
   AND ITEM.D_E_L_E_T_=' '
   LEFT JOIN SYS_USR_FILIAL F ON F.USR_ID=U.USR_ID
   AND F.USR_ACESSO='T'
   AND F.D_E_L_E_T_=' '
   LEFT JOIN SYS_RULES_USR_RULES USRRUL ON USRRUL.USER_ID = U.USR_ID
   AND USRRUL.D_E_L_E_T_ = ''
   LEFT JOIN SYS_RULES RUL ON USRRUL.USR_RL_ID = RUL.RL__ID
   AND RUL.D_E_L_E_T_ = ''
   LEFT JOIN SYS_RULES_FEATURES FEA ON FEA.RL__ID = RUL.RL__ID
   AND RL__ROTINA = F_FUNCTION
   AND FEA.D_E_L_E_T_ = ''
   WHERE U.USR_MSBLQL='2'
     AND U.D_E_L_E_T_=' '
     AND F_FUNCTION IS NOT NULL
     AND U.USR_ID BETWEEN @CUSRDE  AND @CUSRATE
     AND F_FUNCTION BETWEEN @CROTDE AND @CROTATE ) TMP
ORDER BY Codigo,
         Rotina,
         Item
