Select Max(F2_DOC)  From SF2010
Where F2_FILIAL = '01' and F2_DOC Like ('000%') 
And F2_SERIE = '1'
And D_E_L_E_T_= ''

Select D2_PEDIDO,* From SD2010
Where D2_FILIAL = '01' and D2_DOC = '000378596'
And D_E_L_E_T_= ''

--Ordem de separaçãp
Select * From ZZR010
Where ZZR_FILIAL = '01' and ZZR_OS In ('40315901','40336001')
And D_E_L_E_T_= ''

--Ordem de carga 
Select * From ZZ9010
Where ZZ9_FILIAL = '01' and ZZ9_ORDCAR In ('00014409','000144010')
And D_E_L_E_T_= ''

SELECT ZZR.ZZR_ITEMPV AS [ITEM],  SUM(ZZR.ZZR_QUAN) AS [QTD],  (  	SELECT SUM(SC9.C9_QTDLIB)  	
FROM SC9010 SC9  	
WHERE SC9.C9_FILIAL = ZZR.ZZR_FILIAL  	AND SC9.C9_PEDIDO = ZZR.ZZR_PEDIDO  	AND SC9.C9_SEQOS  = ZZR.ZZR_SEQOS  	
AND SC9.C9_ITEM	  = ZZR.ZZR_ITEMPV  	AND SC9.D_E_L_E_T_ = ZZR.D_E_L_E_T_  	AND SC9.C9_BLEST = ''  	AND SC9.C9_BLCRED = ''  ) AS [QTD_SC9]  
FROM ZZR010 ZZR       WHERE ZZR.ZZR_FILIAL = '01'     AND ZZR.ZZR_OS = '40315901'     AND ZZR.D_E_L_E_T_ = ''   
GROUP BY ZZR.ZZR_FILIAL,  ZZR.ZZR_PEDIDO,  ZZR.ZZR_SEQOS,  ZZR.ZZR_ITEMPV,  ZZR.D_E_L_E_T_


SELECT ZZR.ZZR_PEDIDO AS [PEDIDO],    ZZR.ZZR_ITEMPV AS [ITEM],    ZZR.ZZR_SEQOS AS [SEQ],    ISNULL(SC9.R_E_C_N_O_, 0) AS [SC9_REC],    
ISNULL(SC9.C9_CLIENTE, '') AS [CLI],    ISNULL(SC9.C9_LOJA, '') AS [LOJA]    FROM ZZR010 ZZR    LEFT JOIN SC9010 SC9 ON ZZR.ZZR_FILIAL = SC9.C9_FILIAL  
AND ZZR.ZZR_PEDIDO		= SC9.C9_PEDIDO  AND ZZR.ZZR_SEQOS		= SC9.C9_SEQOS  AND ZZR.ZZR_ITEMPV		= SC9.C9_ITEM  
AND ZZR.D_E_L_E_T_		= SC9.D_E_L_E_T_   AND ''					= SC9.C9_BLEST  AND ''					= SC9.C9_BLCRED     
WHERE ZZR.ZZR_FILIAL = '01'    AND ZZR.ZZR_OS = '40315901'    AND ZZR.D_E_L_E_T_ = ''  
GROUP BY ZZR.ZZR_PEDIDO, ZZR.ZZR_ITEMPV, ZZR.ZZR_SEQOS,  ISNULL(SC9.R_E_C_N_O_, 0), ISNULL(SC9.C9_CLIENTE, ''), ISNULL(SC9.C9_LOJA, '')

Select * From SX6010
Where X6_VAR In ('MV_CDROMA','MV_CDCARGA')

Select * From SC5010
Where C5_NUM = '403159'
And D_E_L_E_T_= ''


Select * From SC6010
Where C6_NUM = '403159'
And D_E_L_E_T_= ''


-- Tabelas
Select * From SX2010
Where X2_CHAVE In ('DA3','DA4','SA1','DUT')
And D_E_L_E_T_= ''

-- Veiculos 
Select * From DA3010
Where D_E_L_E_T_= ''

-- Motoristas 
Select * From DA4010
Where D_E_L_E_T_= ''

-- Tipos veiculos 
Select * From DUT010

