SELECT   SUBSTRING(E5_USERLGI, 3, 1) + SUBSTRING(E5_USERLGI, 7, 1) +
         SUBSTRING(E5_USERLGI, 11, 1) + SUBSTRING(E5_USERLGI, 15, 1) +
         SUBSTRING(E5_USERLGI, 2, 1) + SUBSTRING(E5_USERLGI, 6, 1) +
         SUBSTRING(E5_USERLGI, 10, 1) + SUBSTRING(E5_USERLGI, 14, 1) +
         SUBSTRING(E5_USERLGI, 1, 1) + SUBSTRING(E5_USERLGI, 5, 1) +
         SUBSTRING(E5_USERLGI, 9, 1) + SUBSTRING(E5_USERLGI, 13, 1) +
         SUBSTRING(E5_USERLGI, 17, 1) + SUBSTRING(E5_USERLGI, 4, 1) +
         SUBSTRING(E5_USERLGI, 8, 1) USUARIO_INCLUSAO,
		 SUBSTRING(E5_USERLGI, 3, 1) + SUBSTRING(E5_USERLGA, 7, 1) +
         SUBSTRING(E5_USERLGI, 11, 1) + SUBSTRING(E5_USERLGA, 15, 1) +
         SUBSTRING(E5_USERLGI, 2, 1) + SUBSTRING(E5_USERLGA, 6, 1) +
         SUBSTRING(E5_USERLGI, 10, 1) + SUBSTRING(E5_USERLGA, 14, 1) +
         SUBSTRING(E5_USERLGI, 1, 1) + SUBSTRING(E5_USERLGA, 5, 1) +
         SUBSTRING(E5_USERLGI, 9, 1) + SUBSTRING(E5_USERLGA, 13, 1) +
         SUBSTRING(E5_USERLGI, 17, 1) + SUBSTRING(E5_USERLGA, 4, 1) +
         SUBSTRING(E5_USERLGI, 8, 1) USUARIO_ALTERACAO
FROM SE5010 
WHERE E5_NUMERO IN ('PC14771' ) AND E5_FILORIG = 'BA01'