-- Qtde usuarios
Select USR_QTDACESSOS, * FROM SYS_USR
WHERE USR_MSBLQL='2' AND USR_QTDACESSOS>'1'
AND D_E_L_E_T_=''

--Ultimo acesso usuarios
SELECT USR_DTLOGON,* FROM SYS_USR WHERE USR_MSBLQL='2' AND USR_DTLOGON<'20211220' and D_E_L_E_T_ = '' --and USR_ID in ('000464','000497','000350')
Order By USR_CODIGO