
Declare @FILIAL Char(4), @NUMPC Char(6), @NUMCOT Char(6), @NUMSC Char(6)
SET @FILIAL = 'BA01' 
SET @NUMPC = '009334'
SET @NUMCOT = '007918'
SET @NUMSC = '008630'

-- NF de Entrada - itens
-- Veficar se PC não teve movimentações Fiscais de Entrada
Select D1_TES, D1_PEDIDO,D_E_L_E_T_, * From SD1010 
Where D1_FILIAL = @FILIAL and D1_PEDIDO In (@NUMPC) and D_E_L_E_T_='' 

Select Sum (D1_QUANT) AS Total From SD1010 
Where D1_FILIAL = @FILIAL and D1_PEDIDO in (@NUMPC) and D_E_L_E_T_='' 

-- Pedido Compra
SELECT C7_PO_EIC,C7_NUMIMP, C7_FILIAL, C7_PRODUTO, C7_NUM, C7_NUMCOT, C7_NUMSC, C7_FORNECE, C7_LOJA, C7_QUJE, C7_CONAPRO, C7_QUANT, C7_RESIDUO, C7_ENCER,  * FROM SC7010 
WHERE C7_FILIAL = @FILIAL AND C7_NUM in (@NUMPC) and D_E_L_E_T_ = ''

SELECT Sum (C7_QUANT) AS QUANT, Sum (C7_QUJE) as Entrega   FROM SC7010 
WHERE C7_FILIAL=@FILIAL AND C7_NUM in (@NUMPC) and D_E_L_E_T_ = ''

--Cotações
SELECT C8_FILIAL, C8_PRODUTO, C8_NUMPED,C8_NUM,C8_NUMSC, C8_FORNECE, C8_LOJA, * FROM SC8010 
WHERE C8_FILIAL=@FILIAL AND C8_NUM = @NUMCOT AND D_E_L_E_T_='' and NOT C8_NUMPED = 'XXXXXX' and C8_NUMPED in (@NUMPC)

-- Solicitação de compra
Select C1_FILIAL, C1_PRODUTO, C1_PEDIDO, C1_COTACAO, C1_NUM, C1_FORNECE, C1_LOJA, * From SC1010
Where C1_FILIAL = @FILIAL and C1_NUM = @NUMSC and D_E_L_E_T_ = '' and C1_PEDIDO = @NUMPC

--SW1 - Itens Solicitacao Importacao
Select W1_FABR, W1_FORN, * From SW1010
Where W1_FILIAL = 'BA02' and W1_PO_NUM = 'IMP-23/009-SG' and D_E_L_E_T_ =''

--SW2 - Capa de Purchase Order
Select * From SW2010
Where W2_FILIAL = 'BA02' and W2_PO_NUM = 'IMP-23/009-SG' and D_E_L_E_T_=''

--SW3 - Itens de Purchase Order
Select W3_FORN, W3_FABR, * From SW3010
Where W3_FILIAL = 'BA02' and W3_PO_NUM = 'IMP-23/009-SG' and D_E_L_E_T_ =''


--CAPA DO EMBARQUE IMPORTAÇÃO
SELECT * FROM SW6010 WHERE W6_HAWB='IMP-23/009-SG'

--ITEM DO EMBARQUE IMPORTAÇÃO
SELECT * FROM SW7010 WHERE W7_PO_NUM='IMP-23/009-SG'
--UPDATE SW7010 SET W7_FABR='018987', W7_FORN='018987' WHERE W7_PO_NUM='IMP-22/031-SG'   --016150