DECLARE @DATEINI varchar(8)    
DECLARE @DATEFIM varchar(8)    
SET @DATEINI = '20211001'      --DATA DE EMISSAO INICIAL
SET @DATEFIM = '20211031'      --DATA DE EMISSAO FINAL

SELECT DISTINCT 
C7_FILIAL  EMP_COMPRA,SYS.M0_FILIAL EMPRESA,
CASE WHEN C7_PRODUTO IN ('0200500021','0200500022') THEN 'SOCER PR'  WHEN C7_PRODUTO IN ('0200900003','0200900043') THEN 'ITACOL' ELSE 'A MESMA'END AS LOCAL_ENTREGA,
C7_NUM PEDIDO,C7_CONAPRO LIB_BLOQ,CONVERT (DATE,C7_EMISSAO,12) EMISSAO,CONVERT (DATE,C7_DATPRF,12)  PREV_ENTREGA,A2_NATUREZ NAT_FIN,ED_DESCRIC DESC_FIN, 
CASE WHEN C7_FORNECE IN ('000381') AND C7_LOJA IN ('05') THEN 'NÃO CONSOME' ELSE 'CONSOME' END AS LIMITE,
C7_PRODUTO PRODUTO,B1_DESC DESCRICAO,C7_UM UND,C7_QUANT QUANTIDADE,C7_PRECO VLR_UNIT,C7_TOTAL VLR_TOTAL,C7_QUJE ENTREGUE,C7_FORNECE FORNEC,C7_LOJA LOJA,
A2_NOME NOME,A2_ZZTPFOR TIPO,E4_DESCRI VENCTO,C7_RESIDUO RESIDUO,
CASE WHEN C7_RESIDUO = 'S' THEN (C7_QUANT-C7_QUJE)*C7_PRECO ELSE  '' END AS VR_RESIDUO,
CASE WHEN C7_RESIDUO = 'S' THEN (C7_QUANT-C7_QUJE) ELSE '' END AS QUANT_RESIDUO,
CASE WHEN C7_RESIDUO = 'S' THEN (C7_QUANT-(C7_QUANT-C7_QUJE)) WHEN C7_RESIDUO = ' ' THEN C7_QUANT END AS SALDO_COMPRA,
C7_OBS OBSERV,C7_ZZCNOME
FROM SC7010 SC7 WITH (NOLOCK)
INNER JOIN SYS_COMPANY SYS (NOLOCK) ON M0_CODFIL=C7_FILIAL AND SYS.D_E_L_E_T_= ' '
INNER JOIN SA2010 SA2 (NOLOCK) ON A2_COD=C7_FORNECE AND A2_LOJA=C7_LOJA AND SA2.D_E_L_E_T_=''
INNER JOIN SB1010 SB1 (NOLOCK) ON B1_COD=C7_PRODUTO AND SB1.D_E_L_E_T_=''
INNER JOIN SE4010 SE4 (NOLOCK) ON E4_CODIGO=C7_COND AND SE4.D_E_L_E_T_=''
INNER JOIN SED010 SED (NOLOCK) ON ED_CODIGO=A2_NATUREZ AND SED.D_E_L_E_T_=''

WHERE C7_APROV = '000050' AND SC7.D_E_L_E_T_=' '
  AND C7_EMISSAO BETWEEN @DATEINI AND @DATEFIM
ORDER BY 1,2

SELECT CS_FILIAL FILIAL,CS_COD APROVADOR,CONVERT (DATE,CS_DATA,12) DATA,CS_SALDO  SALDO FROM SCS010 SCS 
WHERE CS_COD = '000011'  AND CS_DATA = '20211001'  AND SCS.D_E_L_E_T_=' ' ORDER BY 1


--SELECT * FROM SCS010 where CS_COD = '000011' AND CS_FILIAL = 'BA10'
--UPDATE SCS010 SET CS_SALDO =  '1980659.90' WHERE CS_COD = '000011' AND CS_DATA = '20211001' AND CS_FILIAL = 'BA10'

  

  