-- Emepnhos e Reservas
-- Correção de Empenhos e Reservas
-- SDC - Composicao do Empenho
--SBF - Saldos por Endereco

Select * From SDC010
Select * From SBF010

--Update SBF010 set BF_EMPENHO = 
		(SELECT ISNULL(SUM(DC.DC_QUANT),0) QTDDC
		FROM SDC010 DC
		WHERE BF_FILIAL = DC_FILIAL
		AND BF_PRODUTO = DC_PRODUTO
		AND BF_LOCAL = DC_LOCAL
		AND BF_LOCALIZ = DC_LOCALIZ
		AND BF.D_E_L_E_T_ = DC.D_E_L_E_T_)
FROM SBF010 BF
WHERE BF_FILIAL IN ('01','02')
AND BF_EMPENHO <> 
		(SELECT ISNULL(SUM(DC_E.DC_QUANT),0) QTDDC
		FROM SDC010 DC_E
		WHERE BF_FILIAL = DC_FILIAL
		AND BF_PRODUTO = DC_PRODUTO
		AND BF_LOCAL = DC_LOCAL
		AND BF_LOCALIZ = DC_LOCALIZ
		AND BF.D_E_L_E_T_ = DC_E.D_E_L_E_T_)
AND BF.D_E_L_E_T_ = ''
