
Declare @D3_TMENT Real, @D3_TMSAI Real, @D5_TMENT Real, @D5_TMSAI Real,
@D1_ENT Real, @D2_SAI Real , @SDD_QTDE Real, @B9_QTDEINI Real, @BJ_QTDEINI Real,
@PROD Char(10), @FIL Char(4), @DTINI Char(8), @DTFIM Char(8), @DTREF Char(8)

Set @PROD = '5101000606'
Set @FIL = 'BA12'
Set @DTINI = '20230101'
Set @DTFIM = '20230123'
Set @DTREF = '20221231'

-- Saldo Fisico e Financeiro (Estoque)
Select B2_FILIAL, B2_COD,B1_RASTRO,B1_TIPO,B1_TIPOCQ,B1_NOTAMIN, B1_DESC, B2_LOCAL, B2_QATU, SUM(B8_SALDO) B8_SOMA,B1_UM,

D3_TMENT = (SELECT Sum(D3_QUANT) FROM SD3010 WHERE D3_FILIAL = @FIL AND D3_COD = @PROD  AND D_E_L_E_T_ = ''
And D3_EMISSAO Between @DTINI and @DTFIM and D3_TM <= '500' And D3_ESTORNO = ''),

D3_TMSAI = (SELECT Sum(D3_QUANT) FROM SD3010 WHERE D3_FILIAL = @FIL AND D3_COD = @PROD  AND D_E_L_E_T_ = ''
And D3_EMISSAO Between @DTINI and @DTFIM and D3_TM >= '500' and D3_ESTORNO = ''),

D5_TMENT = (SELECT Sum(D5_QUANT) FROM SD5010 WHERE D5_FILIAL = @FIL AND D5_PRODUTO = @PROD  AND D_E_L_E_T_ = ''
And D5_DATA Between @DTINI and @DTFIM and D5_ORIGLAN <= '500' And D5_ESTORNO = ''),

D5_TMSAI = (SELECT Sum(D5_QUANT) FROM SD5010 WHERE D5_FILIAL = @FIL AND D5_PRODUTO = @PROD  AND D_E_L_E_T_ = ''
And D5_DATA Between @DTINI and @DTFIM and D5_ORIGLAN >= '500' And D5_ESTORNO = ''),

D1_ENT = (SELECT Sum(D1_QUANT) FROM SD1010 WHERE D1_FILIAL = @FIL AND D1_COD = @PROD  AND D_E_L_E_T_ = ''
And D1_DTDIGIT Between @DTINI and @DTFIM),

D2_SAI = (Select Sum(D2_QUANT) FROM SD2010 WHERE D2_FILIAL = @FIL AND D2_COD = @PROD  AND D_E_L_E_T_ = ''
And D2_EMISSAO Between @DTINI and @DTFIM),

SDD_QTDE = (Select Sum(DD_QUANT) From SDD010 Where DD_PRODUTO = @PROD and DD_FILIAL = @FIL 
And DD_SALDO > 0 and D_E_L_E_T_=''),

B9_QTDEINI = (SELECT Sum(B9_QINI) FROM SB9010 WHERE B9_FILIAL = @FIL AND B9_COD = @PROD AND D_E_L_E_T_ = '' 
And B9_DATA = @DTREF And B9_QINI > 0),

BJ_QTDEIN = (SELECT Sum(BJ_QINI) FROM SBJ010 WHERE BJ_FILIAL = @FIL AND BJ_COD = @PROD AND D_E_L_E_T_ = '' 
And BJ_DATA = @DTREF And BJ_QINI > 0)

From SB2010 SB2

--SB8 - Saldos por Lote
Left Join SB8010 SB8
ON B8_PRODUTO = B2_COD	
And B8_FILIAL = B2_FILIAL
And B8_LOCAL = B2_LOCAL
And SB8.D_E_L_E_T_ = ''

--SB1 - Cadastro de Produtos
Inner Join SB1010 SB1
ON B1_COD = B2_COD	
And SB1.D_E_L_E_T_ = ''

/*--SD3 - Movimentacoes Internas
Inner Join SD3010 SD3
On D3_COD = B2_COD
And D3_FILIAL= B2_FILIAL
And D3_EMISSAO Between '20221101' and '20221130'
And D3_ESTORNO = ''
And SD3.D_E_L_E_T_ =''*/


Where B2_COD In (@PROD) and SB2.D_E_L_E_T_ = '' and B2_FILIAL = @FIL and B2_QATU >= 0
GROUP BY B2_FILIAL, B2_COD,B1_DESC,B1_RASTRO,B1_TIPOCQ,B1_NOTAMIN, B1_TIPO, B2_LOCAL, B2_QATU,B1_UM

