-- Ajuste SB6 quando tem diferença no Fechameno de Custos
-- SB6 Desbalanceada 

SELECT D1_CUSTO, B6_CUSTO1, D1_QUANT, B6_QUANT, *
--UPDATE SB6010 SET B6_CUSTO1 = D1_CUSTO, B6_QUANT = D1_QUANT
FROM SB6010 B6
INNER JOIN SD1010 D1 ON D1_FILIAL = B6_FILIAL AND B6_IDENT = D1_IDENTB6 AND D1_DOC = B6_DOC AND D1_SERIE = B6_SERIE AND D1_COD = B6_PRODUTO /*AND D1_QUANT = B6_QUANT*/ AND D1.D_E_L_E_T_ = B6.D_E_L_E_T_
WHERE B6_FILIAL = '01'
--AND B6_IDENT = 'Sw358J'
AND B6.D_E_L_E_T_ = ''