SELECT B2_FILIAL, B2_COD, B2_LOCAL, B2_QATU, SUM(B8_SALDO) B8_SOMA, B2_QATU-SUM(B8_SALDO) DIFERENCA,
	
Case 
When B2_QATU = Sum(B8_SALDO) Then 'Certo'
Else 'Errado'
End AS Status_

FROM SB2010 
	INNER JOIN SB8010 ON B8_FILIAL=B2_FILIAL 
	AND B8_PRODUTO=B2_COD 
	AND B8_LOCAL=B2_LOCAL 
	AND SB8010.D_E_L_E_T_='' 
	AND B8_SALDO>0
WHERE  SB2010.D_E_L_E_T_='' AND B2_QATU>0
GROUP BY B2_FILIAL, B2_COD, B2_LOCAL, B2_QATU
ORDER BY 6 Desc