--Clientes que ´ja faturaram por uma Filial
SELECT DISTINCT
	A1_COD CODIGO, 
	A1_LOJA LOJA, 
	A1_NOME RAZAO_SOCIAL, 
	A1_END ENDERECO, 
	A1_MUN CIDADE, 
	A1_BAIRRO BAIRRO, 
	A1_DDD DDD, 
	A1_TEL TELEFONE,
	A1_CONTATO CONTATO, 
	A1_ULTCOM ULTIMA_COMPRA
FROM SA1010 
INNER JOIN SF2010 ON F2_CLIENTE=A1_COD AND F2_LOJA=A1_LOJA AND SF2010.D_E_L_E_T_='' AND F2_FILIAL='BA01'
WHERE SA1010.D_E_L_E_T_='' AND A1_EST <> 'EX'



SELECT TOP 10 * FROM SF2010
SELECT TOP 10 * FROM SA1010