-- Clientes por UF.
SELECT A1_COD CODIGO, A1_LOJA LOJA, A1_NOME RAZAO_SOCIAL, A1_END ENDERECO, A1_MUN CIDADE, A1_BAIRRO BAIRRO, A1_DDD DDD, A1_TEL TELEFONE,
 A1_CONTATO CONTATO, A1_ULTCOM ULTIMA_COMPRA
FROM SA1010 WHERE A1_EST='SP' AND D_E_L_E_T_=''

