SELECT * FROM (
SELECT Round(SUM(D2_TOTAL + D2_VALFRE),2) TOTAL,D2_FILIAL,D2_DOC,D2_SERIE,D2_CLIENTE, D2_LOJA FROM SD2010 SD2 
WHERE 
--D2_FILIAL = 'BA19' AND
D2_TIPO = 'D' AND 

D2_VALFUN > 0 AND
SD2.D_E_L_E_T_ = ''
GROUP BY D2_FILIAL,D2_DOC,D2_SERIE,D2_CLIENTE, D2_LOJA
) TMP
INNER JOIN SE2010 SE2 ON E2_FILORIG = D2_FILIAL AND E2_TIPO = 'NDF'
--Inner Join SA2010 SA2 ON E2_FORNECE = A2_COD
AND E2_NUM = D2_DOC AND E2_PREFIXO = D2_SERIE AND E2_FORNECE = TMP.D2_CLIENTE AND E2_LOJA = D2_LOJA AND SE2.D_E_L_E_T_ = '' AND E2_SALDO>0
WHERE
TOTAL <> E2_VALOR 