
--NF Saida Cab.
--Select D_E_L_E_T_,F2_EMISSAO, F2_DTLANC, F2_CLIENT, F2_CLIENTE, * From SF2010
--Where F2_FILIAL <> '' and F2_ESPECI1 = 'DEVOLUCAO' and D_E_L_E_T_=''

--NF Saida Itens
--Select D_E_L_E_T_,D2_EMISSAO,D2_NFORI, D2_TES, * From SD2010
--Where D2_FILIAL <> '' and D2_NFORI <> ''  and D_E_L_E_T_=''

--SE2 - Contas a Pagar
--Select E2_NUM,E2_TIPO, E2_SALDO, E2_VALOR,E2_VLCRUZ,E2_BASECOF,E2_BASEPIS,E2_BASECSL,E2_BASEINS,E2_BASEIRF,E2_BASEISS, * From SE2010
--Where E2_FILORIG <> '' and D_E_L_E_T_ = '' and E2_TIPO In ('NDF') 


-- Tabelas 
-- SF1 - NF Entrada Cab.
-- SD1 -- NF Entrada Itens
-- SF2 - NF Saida Cab.
-- SD2 -- NF Saida Itens
-- SE2 - Conras a Pagar 
-- SA2 - Fornecedor
-- SE4 - Cond. de pagamento
-- SYS_COMPANY - Empresa




-- NF Saida Cab.
Select SF2.F2_FILIAL, SYS_COMPANY.M0_FILIAL,SA2.A2_CGC, SA2.A2_COD, SA2.A2_NOME, SE2.E2_NUM,SF2.F2_DOC, SD2.D2_DOC, SD2.D2_NFORI, SF1.F1_DOC, SD1.D1_DOC,
SE2.E2_VALOR,SF2.F2_VALBRUT, DIFERENCA = (SE2.E2_VALOR - SF2.F2_VALBRUT),GILRATE_VALSENAR = (SF2.F2_CONTSOC+SF2.F2_VLSENAR), E2_SALDO,
VL_SEM_IMPOSTOS = (SF2.F2_VALBRUT-(SF2.F2_CONTSOC+SF2.F2_VALINSS+SF2.F2_VLSENAR)),
IMPOSTOS = (SF2.F2_CONTSOC+SF2.F2_VALINSS+SF2.F2_VLSENAR),SF2.F2_VALINSS,SF2.F2_CONTSOC, SF2.F2_VLSENAR,SF2.F2_FRETE, SF2.F2_EMISSAO,

	Case 
	When SE2.E2_VALOR = (SF2.F2_VALBRUT) Then 'CERTO'
	Else 'ERRADO'
	End AS STATUS_

From SF2010 SF2

	-- SE2 Contas a pagar
	Inner Join SE2010 SE2 With(Nolock)
	ON SE2.E2_NUM = SF2.F2_DOC
	And SE2.E2_FILORIG = SF2.F2_FILIAL
	And SE2.E2_FORNECE = SF2.F2_CLIENTE
	And SE2.E2_LOJA = SF2.F2_LOJA
	And SE2.D_E_L_E_T_ =''

	-- SD2 - Itens da NF
	Inner Join SD2010 SD2 With(Nolock)
	ON SD2.D2_DOC = SF2.F2_DOC
	And SD2.D2_FILIAL = SF2.F2_FILIAL
	And SD2.D2_CLIENTE = SF2.F2_CLIENTE
	And SD2.D2_LOJA = SF2.F2_LOJA
	And SD2.D_E_L_E_T_ =''

	--SF1 - Cab. da NF Entrada
	Inner Join SF1010 SF1 With(Nolock)
	ON SF1.F1_DOC = SD2.D2_NFORI
	And SF1.F1_FILIAL = SD2.D2_FILIAL
	And SF1.F1_FORNECE = SD2.D2_CLIENTE
	And SF1.F1_LOJA = SD2.D2_LOJA
    And SF1.D_E_L_E_T_ =''

	 --SD1 - Itens da NF - Entrada 
	Inner Join SD1010 SD1 With(Nolock)
	ON SD1.D1_DOC = SF1.F1_DOC
	And SD1.D1_FILIAL = SF1.F1_FILIAL
	And SD1.D1_FORNECE = SF1.F1_FORNECE
	And SD1.D1_LOJA = SF1.F1_LOJA
	And SD1.D_E_L_E_T_ =''

    --Empresa
  	Inner Join SYS_COMPANY SYS_COMPANY With (NOLOCK)
	On SYS_COMPANY.M0_CODFIL = SF2.F2_FILIAL
	And SYS_COMPANY.D_E_L_E_T_ =''

	-- Fornecedor
	Inner Join SA2010 SA2 With (NOLOCK)
	ON SA2.A2_COD = SF2.F2_CLIENTE
	And SA2.A2_LOJA = SF2.F2_LOJA
	And SA2.D_E_L_E_T_ =''
	

	-- Condição de Pagamento
	Inner Join SE4010 SE4 With (NOLOCK)
	ON SE4.E4_CODIGO = SF2.F2_COND
	And SE4.D_E_L_E_T_ =''

Where F2_FILIAL Between 'BA19' and 'BA19' and E2_TIPO = 'NDF' and SF2.D_E_L_E_T_='' and F2_DUPL <> ''
and F2_DOC Between '000000905' and '000000906' and F2_EMISSAO >= '20221015' 
--and F2_CLIENTE In ('005043','007156')
Order BY 24 Desc
