 --Query Final Luis Felipe
SELECT 
	A.C6_FILIAL      AS C6_FILIAL,
	A.C6_NUM         AS C6_NUM,
	A.C6_ITEM        AS C6_ITEM,
	A.C6_PRODUTO     AS C6_PRODUTO,
	SUM(A.C6_QTDVEN) AS C6_QTDVEN,
	A.C6_ACONDIC     AS C6_ACONDIC,
	SUM(A.C6_LANCES) AS C6_LANCES,
	A.C6_METRAGE     AS C6_METRAGE,
	SUM(C6_VALOR)    AS C6_VALOR,
	A.C6_TES         AS C6_TES,
	A.C6_LOCAL       AS C6_LOCAL,
	A.C6_CLI         AS C6_CLI,
	A.C6_LOJA        AS C6_LOJA,
	A.C6_ZZPVORI     AS C6_ZZPVORI,
	A.C6_ENTREG      AS C6_ENTREG,
	A.C6_SEMANA      AS C6_SEMANA,
	A.C6_PRCVEN      AS C6_PRCVEN,
	A.RCNO           AS RCNO
FROM
(
SELECT
	C6.C6_FILIAL,
	C6.C6_NUM,
	CASE
		WHEN C6.C6_ITEMIMP <> '' THEN C6.C6_ITEMIMP
		ELSE C6.C6_ITEM
	END AS C6_ITEM,
	LEFT(C6.C6_PRODUTO,10) AS C6_PRODUTO,
	C6.C6_QTDVEN,
	C6.C6_ACONDIC,
	C6.C6_LANCES,
	C6.C6_METRAGE,
	C6.C6_VALOR,
	C6.C6_ITEMIMP,
	C6.C6_TES,
	C6.C6_LOCAL,
	C6.C6_CLI,
	C6.C6_LOJA,
	C6.C6_ZZPVORI,
	C6.C6_ENTREG,
	C6.C6_SEMANA,
	C6.C6_PRCVEN, 
	RCNO = (SELECT MIN(SC6IND.R_E_C_N_O_) FROM SC6010 SC6IND WITH(NOLOCK)
			WHERE SC6IND.C6_FILIAL IN ('01','02','03')
			  AND SC6IND.C6_NUM = C6.C6_NUM
			  AND SC6IND.C6_ZZPVORI = C6.C6_ZZPVORI
			  AND SC6IND.D_E_L_E_T_ = '')
FROM SC6010 C6

INNER JOIN SC5010 C5
ON  C6.C6_FILIAL		= C5.C5_FILIAL
AND C6.C6_NUM			= C5.C5_NUM
AND C6.D_E_L_E_T_		= C5.D_E_L_E_T_

WHERE C6.C6_FILIAL IN ('01','02','03') 
AND C6.C6_NUM = '107473'
AND C6.C6_ITEM <> '' 
AND ( C6.C6_LOCAL = '10' OR C6.C6_SEMANA = 'TAUTOM' ) 
AND C6.D_E_L_E_T_ = ''
) A

GROUP BY C6_FILIAL, C6_NUM, C6_ITEM, C6_PRODUTO, C6_ACONDIC, C6_METRAGE, C6_TES, 
C6_LOCAL, C6_CLI, C6_LOJA, C6_ZZPVORI, C6_ENTREG, C6_SEMANA, C6_PRCVEN, RCNO

ORDER BY C6_ZZPVORI DESC



--Query final Alexandre
SELECT
SC6.C6_FILIAL,
SC6.C6_NUM,
CASE
	WHEN SC6.C6_ITEMIMP <> ''
		THEN SC6.C6_ITEMIMP
	ELSE SC6.C6_ITEM
END AS C6_ITEM,
SUBSTRING(SC6.C6_PRODUTO,1,10) AS C6_PRODUTO,
SUM(SC6.C6_QTDVEN) AS C6_QTDVEN,
SC6.C6_ACONDIC,
SUM(SC6.C6_LANCES) AS C6_LANCES,
SC6.C6_METRAGE,
SUM(SC6.C6_VALOR) AS C6_VALOR,
SC6.C6_TES,
SC6.C6_LOCAL,
SC6.C6_CLI,
SC6.C6_LOJA,
SC6.C6_ZZPVORI,
SC6.C6_ENTREG,
SC6.C6_SEMANA,
SC6.C6_PRCVEN,
CASE
	WHEN SC6.C6_ITEMIMP <> ''
		THEN SSC6.R_E_C_N_O_ 
	ELSE SC6.R_E_C_N_O_ 
END AS R_E_C_N_O_

FROM SC6010 SC6

INNER JOIN SC5010 SC5
ON SC6.C6_FILIAL		= SC5.C5_FILIAL
AND SC6.C6_NUM			= SC5.C5_NUM
AND SC6.D_E_L_E_T_		= SC5.D_E_L_E_T_

LEFT JOIN SC6010 SSC6 
ON SSC6.C6_FILIAL 		= SC6.C6_FILIAL
AND SSC6.C6_NUM 		= SC6.C6_NUM
AND SSC6.C6_ITEM 		= SC6.C6_ITEMIMP
AND SSC6.D_E_L_E_T_ 	= SC6.D_E_L_E_T_

WHERE SC6.C6_FILIAL = '02' 
AND SC6.C6_NUM = '107473'
AND SC6.C6_ITEM <> ''
AND ( SC6.C6_LOCAL = '10' OR SC6.C6_SEMANA = 'TAUTOM' )
AND SC6.D_E_L_E_T_ = ''
GROUP BY SC6.C6_FILIAL,
SC6.C6_NUM,
CASE
	WHEN SC6.C6_ITEMIMP <> ''
		THEN SC6.C6_ITEMIMP
	ELSE SC6.C6_ITEM
END,
SUBSTRING(SC6.C6_PRODUTO,1,10),
SC6.C6_ACONDIC,
SC6.C6_METRAGE,
SC6.C6_TES,
SC6.C6_LOCAL,
SC6.C6_CLI,
SC6.C6_LOJA,
SC6.C6_ZZPVORI,
SC6.C6_ENTREG,
SC6.C6_SEMANA,
SC6.C6_PRCVEN,
CASE
	WHEN SC6.C6_ITEMIMP <> ''
		THEN SSC6.R_E_C_N_O_ 
	ELSE SC6.R_E_C_N_O_ 
END
ORDER BY SC6.C6_ZZPVORI DESC

