--Alterar Status Emabarque 
--EEC - Embarque
SELECT EEC_STATUS, EEC_STTDES, * FROM EEC010 
WHERE EEC_FILIAL = 'DB01' AND EEC_PREEMB IN ('1381/22')

--UPDATE EEC010 SET EEC_STATUS='A', EEC_STTDES='Cambio Contratado' WHERE EEC_FILIAL = 'DB01' AND EEC_PREEMB IN ('1381/22')