--Contas a pagar x NF Entrada
Select F1_FILIAL,F1_DOC,F1_FORNECE,F1_LOJA,
Count(E2_PARCELA) As QTDE_PARC,

Count(E2_PARCELA) * Sum (E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL) As E2_IMP_RET,
Sum(F1_ISS+F1_VALIRF+F1_INSS) As F1_IMP_FISCAL,

Count(E2_PARCELA) * Sum(E2_PIS+E2_COFINS+E2_CSLL) As E2_IMP_BASE,
Sum(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) as F1_IMP_BASE_FISCAL,

(Count(E2_PARCELA)*Sum(E2_PIS+E2_COFINS+E2_CSLL)) - Sum(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) as F1__E2_PCC_DIF,
(Count(E2_PARCELA)*Sum(E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL)) - Sum(F1_ISS+F1_VALIRF+F1_INSS) As F1_E2_IMP_RET_DIF,


(Count(E2_PARCELA)*Sum(E2_PIS+E2_COFINS+E2_CSLL)) - Sum(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) -
(Count(E2_PARCELA)*Sum(E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL)) - Sum(F1_ISS+F1_VALIRF+F1_INSS) As F1_E2_IMP_DIF_GERAL,


Sum (E2_VRETISS) As E2_ISS_RET,
Sum (E2_VRETIRF) AS E2_IRF_RET,
Sum (E2_VRETPIS) As E2_PIS_RET,
Sum (E2_VRETINS) As E2_INSS_RET,
Sum (E2_VRETCOF) As E2_COF_RET,
Sum (E2_VRETCSL) As E_CSL_RET_,
Sum (E2_PIS) as E2_PIS,
Sum (E2_COFINS) As E2_COFINS,
Sum (E2_CSLL) As E2_CSLL,

Sum (F1_ISS) As F1_ISS,
Sum (F1_VALIRF) As F1_VALIRF,
Sum (F1_INSS) As F1_INSS,
Sum (F1_VALPIS) As F1_VALPIS,
Sum (F1_VALCOFI) As F1_VALCOFI,
Sum (F1_VALCSLL) As F1_VALCSLL


From SF1010 SF1 -- Contas a pagar

	-- Genericas
	Left Join SX5010 SX5
	On SX5.X5_TABELA = '42'
	And SX5.X5_FILIAL = F1_FILIAL
	And SX5.X5_CHAVE = F1_ESPECIE
	And SX5.D_E_L_E_T_ = ''

	--NF Entrada Cab.
	Left Join SE2010 SE2
	On F1_FILIAL = E2_FILIAL
	And F1_DOC = E2_NUM
	And F1_FORNECE = E2_FORNECE
	And F1_LOJA = E2_LOJA
	And SE2.D_E_L_E_T_ = ''
	   
Where F1_EMISSAO Between '20240301' and '20240331' and E2_EMISSAO Between '20240301' and '20240331'
and SF1.D_E_L_E_T_ = ''

Group By F1_FILIAL,F1_DOC,F1_FORNECE,F1_LOJA
--E2_VRETISS,E2_VRETIRF,E2_VRETPIS,E2_VRETINS,E2_VRETCOF,E2_VRETCSL,
--F1_ISS,F1_VALIRF,F1_INSS,
--E2_PIS,E2_COFINS,E2_CSLL,
--F1_VALPIS,F1_VALCOFI,F1_VALCSLL

Having (Count(E2_PARCELA)*Sum(E2_PIS+E2_COFINS+E2_CSLL)) - Sum(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) <> 0
Or (Count(E2_PARCELA)*Sum(E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL)) - Sum(F1_ISS+F1_VALIRF+F1_INSS) <> 0
--Or (Count(E2_PARCELA)*Sum(E2_PIS+E2_COFINS+E2_CSLL)) - Sum(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) -
--(Count(E2_PARCELA)*Sum(E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL)) - Sum(F1_ISS+F1_VALIRF+F1_INSS) <> 0

Order By 1,3,4,2 