SELECT 
	A.CLIENTE AS [CLIENTE],
	A.LOJA AS [LOJA],
	A.NOME AS [NOME],
	FORMAT(CONVERT(DATETIME,A.DATA_), 'dd/MM/yyyy') AS [DATA],
	A.HORA AS [HORA],
	ZZI.ZZI_PEDIDO AS [PEDIDO],
	SC5.C5_TOTAL AS [VLR_TOTAL],
	A.MOTIVO AS [MOTIVO],
	A.HISTORICO AS [HISTORICO],
	A.FILIAL AS [FILIAL],
	A.UNIDADE AS [UNIDADE],
	A.USUARIO AS [USUARIO]
FROM
(	SELECT
		ZZ1.ZZ1_CLIENT  AS [CLIENTE],
		ZZ1.ZZ1_LOJA    AS [LOJA],
		ZZ1.ZZ1_NOME    AS [NOME],
		ZZ1.ZZ1_DATA    AS [DATA_],
		ZZ1.ZZ1_HORA    AS [HORA],	
		ZZ1.ZZ1_DESCMO  AS [MOTIVO],
		ISNULL(CAST(CAST(ZZ1.ZZ1_HIST AS VARBINARY(8000)) AS VARCHAR(8000)),'') AS [HISTORICO],
		CASE
			WHEN ZZ1.ZZ1_UNID LIKE 'Matriz         ' THEN '01'
			WHEN ZZ1.ZZ1_UNID LIKE 'Filial Tres Lag' THEN '02'
			ELSE '03'
		END AS [FILIAL],
		ZZ1.ZZ1_UNID    AS [UNIDADE],
		ZZ1.ZZ1_USUARI  AS [USUARIO]
	FROM ZZ1010 ZZ1
	WHERE ZZ1.D_E_L_E_T_ = ''
	AND ZZ1.ZZ1_MOTIVO = 'RPR'
	--AND ZZ1.ZZ1_UNID NOT IN ('Matriz         ','Filial Tres Lag'/*,'Filial Extrema-','Filial Pouso Al'*/) 
	--AND ZZ1.ZZ1_CLIENT = '043862'
) A

INNER JOIN ZZI010 ZZI 
ON  ZZI.ZZI_FILIAL	= A.FILIAL
AND ZZI.ZZI_CODCLI	= A.CLIENTE
AND ZZI.ZZI_LOJCLI	= A.LOJA
AND ZZI.ZZI_DATA	= A.DATA_
AND ZZI.ZZI_CODEVE	= '10'
AND ZZI.D_E_L_E_T_	= ''

LEFT JOIN SC5010 SC5
ON  SC5.C5_FILIAL	= ZZI.ZZI_FILIAL
AND SC5.C5_NUM		= ZZI.ZZI_PEDIDO
AND SC5.C5_CLIENTE	= ZZI.ZZI_CODCLI
AND SC5.C5_LOJACLI	= ZZI.ZZI_LOJCLI 
--AND SC5.D_E_L_E_T_	= ''

--WHERE SC5.C5_TOTAL > 0

GROUP BY A.CLIENTE, A.LOJA, A.NOME, A.DATA_ , A.HORA, ZZI.ZZI_PEDIDO, SC5.C5_TOTAL, A.MOTIVO, A.HISTORICO, A.FILIAL, A.UNIDADE, A.USUARIO