-- Verificador CTEx NF Entrada x NF Saida x Financeiro x TES x Fornecedor x Transportadora x Ordem de Carga 
 -- NF Entrada Cab
Select Distinct  F1_FILIAL,F1_ESPECIE,F1_DOC,F1_DUPL,E2_NUM,F2_DOC,ZZ9_DOC,
E2_VALOR,F1_VALBRUT,F1_VALMERC, F1_VALPEDG,GXG_PEDAG,(F1_VALBRUT-F1_VALMERC) As DIF,
D1_TES,F4_TEXTO, F4_AGRPEDG,
(F1_VALPEDG-GXG_PEDAG) As DIF_PEDG,
F1_VALICM,F1_VALIMP5,F1_VALIMP6,D1_COD,
F1_FORNECE,F2_TRANSP,ZZ9_TRANSP,A2_CGC,A2_NOME,A4_CGC,A4_NOME,E2_FORNECE,E2_NOMFOR,
GXG_CTE,GXH_NRIMP,GXG.GXG_NRIMP,F2_CHVNFE,GXH_DANFE,
ISNULL(CONVERT(VARCHAR(8000), CONVERT(VARBINARY(8000), ZZ9_JSCTE)),'') AS [CTE],
F2_VALBRUT,F2_PBRUTO,IsNull(NullIf(F2_VALBRUT,0)/NullIf(F2_PBRUTO,0),0) As VAL_KG,
	
	
	Case 
	When F1_VALMERC <> E2_VALOR Then 'CALC C/ PEDAGIO'
	When F1_VALMERC = E2_VALOR Then 'CALC S/ PEDAGIO'
	Else 'ANALISAR'
	End AS Status_ 


From SF1010 SF1 With(NoLock)

	-- Contas a pagar
	Inner Join SE2010 SE2 With(NoLock)
	On E2_FILIAL = F1_FILIAL
	And E2_LOJA = F1_LOJA
	And E2_NUM = F1_DOC
	And E2_FORNECE = F1_FORNECE
	And SE2.D_E_L_E_T_ = ''

	--NF Entrada Itens 
	Inner Join SD1010 SD1 With(NoLock)
	On D1_FILIAL = F1_FILIAL
	And D1_LOJA = F1_LOJA
	And D1_DOC = F1_DOC
	And D1_FORNECE = F1_FORNECE
	And D1_LOJA = F1_LOJA
	And SD1.D_E_L_E_T_ = ''
	
	-- GXG - EDI - Documento de Frete
	Inner Join GXG010 GXG With(NoLock)
	On GXG.GXG_FILIAL = F1_FILIAL
	And GXG.GXG_CTE = F1_CHVNFE
	And GXG.D_E_L_E_T_ = ''

	--GXH - EDI - DOC CARGA DO DOC FRETE
	Inner Join GXH010 GXH With(NoLock)
	On GXH.GXH_FILIAL = GXG.GXG_FILIAL
	And GXH.GXH_NRIMP = GXG.GXG_NRIMP
	And GXH.D_E_L_E_T_ = ''
	--And GXH.GXH_SEQ = '00001'

	-- NF Saida - Cab.
	Left Join SF2010 SF2 With(NoLock)
	On SF2.F2_FILIAL = GXH.GXH_FILIAL
	And SF2.F2_CHVNFE = GXH.GXH_DANFE
--	And SF2.F2_TRANSP = GXG.GXG_EMISDF
	And SF2.D_E_L_E_T_ = ''

	-- NF Saida - Itens 
	Left Join SD2010 SD2 With(NoLock)
	On SD2.D2_FILIAL = SF2.F2_FILIAL
	And SD2.D2_DOC = SF2.F2_DOC
--	And SF2.F2_TRANSP = GXG.GXG_EMISDF
	And SD2.D_E_L_E_T_ = ''

		
	-- Ordem de Carga 
	Left Join ZZ9010 ZZ9 With(NoLock)
	On ZZ9_FILIAL = F2_FILIAL
	And ZZ9_DOC = F2_DOC
	And ZZ9_TRANSP = F2_TRANSP
	And ZZ9.D_E_L_E_T_ =''

	-- Transpotadora
	Left Join SA4010 SA4 With(NoLock)
	On SA4.A4_COD = F2_TRANSP
	And SA4.D_E_L_E_T_ = ''

		-- Fornecedor
	Left Join SA2010 SA2 With(NoLock)
	On SA2.A2_COD = F1_FORNECE
	And SA2.A2_LOJA = F1_LOJA
	And SA2.D_E_L_E_T_ = ''


	-- TES
	Inner Join SF4010 SF4 With(NoLock)
	On F4_CODIGO = D1_TES
	And SF4.D_E_L_E_T_ =''
	
Where F1_FILIAL In ('01','02','03') --and F1_CHVNFE In ('','')--or GXG.GXG_CTE In ('')
And SF1.F1_EMISSAO Between '20231001' and '20231031'
--And (F1_VALPEDG-GXG_PEDAG) > 0
--And SF1.F1_VALMERC <> SE2.E2_VALOR 
--And SE2.E2_BAIXA = '' and SE2.E2_SALDO > 0
--AND GXG.GXG_NRIMP IN ('4A095576264D4E11') 
And SF1.D_E_L_E_T_ =''
Order By  25,3

Select * From SYS_COMPANY

--CAIXAS DIARIOS                
Select ZM_NUMCX,ZM_NUMERO,E2_NUM,ZM_PARCELA,E2_PARCELA,ZM_PREFIXO,E2_PREFIXO,ZM_TIPO,E2_TIPO,ZM_FORNEC,E2_FORNECE,
ZM_VALOR,E2_VALOR,E2_VALLIQ, Round((ZM_VALOR-E2_VALOR),2) As DIF_,Round((E2_VALLIQ-E2_VALOR),2) AS DIF_LIQUI,
E2_JUROS,E2_ACRESC,E2_DECRESC,E2_ORIGEM,

X5_DESCRI,
ZM_VENCTO,E2_VENCTO,E2_BAIXA, DATEDIFF (Day,E2_VENCTO,E2_BAIXA) AS DIF_DIAS,
	Case 
	When Round((ZM_VALOR-E2_VALOR),2) = Round(E2_JUROS,2) Or 
		 Round((ZM_VALOR-E2_VALOR),2) = Round(E2_ACRESC,2)
	Then 'DIF_JUROS_ACRESC'
	When Round((ZM_VALOR-E2_VALOR),2) = Round((E2_JUROS+E2_ACRESC),2) Then 'DIF_SOMA_JUROS_ACRESC'
	Else 'Analisar'
	End As Analise,

* From SZM010 SZM --Caixas
	
	--Contas a pagar
	Inner Join SE2010 SE2
	On ZM_FILIAL = E2_FILIAL
	And ZM_FORNEC = E2_FORNECE
	And ZM_LOJA = E2_LOJA
	And ZM_NUMERO = E2_NUM
	And ZM_PREFIXO = E2_PREFIXO
	And ZM_PARCELA = E2_PARCELA
	And ZM_TIPO = E2_TIPO
	And SE2.D_E_L_E_T_ = ''

	--Genericas 
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = ZM_FILIAL
	And ZM_TIPO = X5_CHAVE
	And SX5.D_E_L_E_T_ = ''
	
Where E2_NUM In ('062024')
and SZM.D_E_L_E_T_ = ''
--ZM_DATA >= '20230901'  And (ZM_VALOR-E2_VALOR) > 1
Order By 25,26 Desc


--Contas a Pagar              
Select ZM_NUMCX,ZM_NUMERO,E2_NUM,ZM_PARCELA,E2_PARCELA,ZM_PREFIXO,E2_PREFIXO,ZM_TIPO,E2_TIPO,ZM_FORNEC,E2_FORNECE,
ZM_VALOR,E2_VALOR,E2_VALLIQ, Round((ZM_VALOR-E2_VALOR),2) As DIF_,Round((E2_VALLIQ-E2_VALOR),2) AS DIF_LIQUI,
E2_JUROS,E2_ACRESC,E2_DECRESC,E2_ORIGEM,

X5_DESCRI,
ZM_VENCTO,E2_VENCTO,E2_BAIXA, DATEDIFF (Day,E2_VENCTO,E2_BAIXA) AS DIF_DIAS,
	Case 
	When Round((ZM_VALOR-E2_VALOR),2) = Round(E2_JUROS,2) Or 
		 Round((ZM_VALOR-E2_VALOR),2) = Round(E2_ACRESC,2)
	Then 'DIF_JUROS_ACRESC'
	When Round((ZM_VALOR-E2_VALOR),2) = Round((E2_JUROS+E2_ACRESC),2) Then 'DIF_SOMA_JUROS_ACRESC'
	Else 'Analisar'
	End As Analise,

* From SE2010 SE2 -- Contas a pagar 
	
	--Caixa
	Left Join SZM010 SZM
	On ZM_FILIAL = E2_FILIAL
	And ZM_FORNEC = E2_FORNECE
	And ZM_LOJA = E2_LOJA
	And ZM_NUMERO = E2_NUM
	And ZM_PREFIXO = E2_PREFIXO
	And ZM_PARCELA = E2_PARCELA
	And ZM_TIPO = E2_TIPO
	And SE2.D_E_L_E_T_ = ''

	--Genericas
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = ZM_FILIAL
	And ZM_TIPO = X5_CHAVE
	And SX5.D_E_L_E_T_ = ''
	
Where E2_NUM In ('062024')
and SZM.D_E_L_E_T_ = ''
--ZM_DATA >= '20230901'  And (ZM_VALOR-E2_VALOR) > 1
Order By 25,26 Desc

--Contas a pagar x NF Entrada
Select E2_NUM,E2_FORNECE,E2_NOMFOR,D1_COD,D1_COD,B1_DESC,
E2_BASECOF,F1_VALBRUT,E2_VALOR,E2_VALLIQ,
E2_ISS,E2_IRRF,E2_PIS,E2_INSS,E2_COFINS,E2_CSLL,
E2_VRETISS,E2_VRETIRF,E2_VRETPIS,E2_VRETINS,E2_VRETCOF,E2_VRETCSL,		
E2_DESCONT,E2_ACRESC,E2_DECRESC,
F1_ICMS,F1_VALIMP5,F1_VALIMP6,F1_INSS,F1_ISS,F1_VALPIS,F1_VALCOFI,F1_VALCSLL,F1_VALIRF,
F1_ICMSRET,F1_IRRF,
(E2_VRETISS+E2_VRETIRF+E2_VRETPIS+E2_VRETINS+E2_VRETCOF+E2_VRETCSL) As IMP_RET,
(F1_ISS+F1_VALIRF+F1_INSS) As IMP_FISCAL,
(E2_PIS+E2_COFINS+E2_CSLL) As IMP_BASE,
(F1_VALPIS+F1_VALCOFI+F1_VALCSLL) as IMP_BASE_FISCAL,
X5_DESCRI,F1_DOC,
* From SE2010 SE2 -- Contas a pagar

	--Genericas
	Left Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = E2_FILIAL
	And E2_TIPO = X5_CHAVE
	And SX5.D_E_L_E_T_ = ''

	--NF Entrada Cab.
	Left Join SF1010 SF1
	On F1_FILIAL = E2_FILIAL
	And F1_DOC = E2_NUM
	And F1_FORNECE = E2_FORNECE
	And F1_LOJA = E2_LOJA
	And SF1.D_E_L_E_T_ = ''


	--NF Entrada Itens
	Left Join SD1010 SD1
	On D1_FILIAL = F1_FILIAL
	And D1_DOC = F1_DOC
	And D1_FORNECE = F1_FORNECE
	And D1_LOJA = F1_LOJA
	And SD1.D_E_L_E_T_ = ''

	Inner Join SB1010 SB1 --Produtos 
	On B1_COD = D1_COD
	And SB1.D_E_L_E_T_ = ''

	   
Where E2_FORNECE In ('V00335') and E2_NUM = '000020309'
and SE2.D_E_L_E_T_ = ''
Order By E2_TIPO


-- Contas a Pagar x Caixa x NF Entrada Cab/Itens x TES x Genericas 
Select IsNull(SX5F1.X5_DESCRI,'') As DESC_ESPECIE,IsNull(SX5E2.X5_DESCRI,'') As DESC_TIPO,E2_TIPO,
IsNull(D1_COD,'') As D1_COD,IsNull(B1_DESC,'') As B1_DESC ,
E2_NUM,IsNull(ZM_NUMERO,'') AS ZM_NUMERO,E2_FORNECE,E2_NOMFOR,E2_VALOR,E2_SALDO,E2_VALLIQ,E2_BAIXA,IsNull(F1_VALBRUT,'') As F1_VALBRUT,
(E2_VALLIQ-E2_VALOR) As DIF_LIQ, (E2_VRETISS+E2_VRETIRF+E2_VRETINS) As IMP_RET,
(E2_PIS+E2_COFINS+E2_CSLL) As IMP_BASE,
E2_VRETPIS,E2_VRETCOF,E2_VRETCSL,E2_VRETISS,E2_VRETIRF,E2_VRETINS,
IsNull(D1_TES,'') As TES, IsNulL(F4_TEXTO,'') As F4_TEXTO
From SE2010 SE2 -- Contas a pagar 

	-- NF Entrada Cab.
	Left Join SF1010 SF1
	On F1_FILIAL = E2_FILIAL
	And F1_FORNECE = E2_FORNECE
	And F1_LOJA = E2_LOJA
	And F1_DOC = E2_NUM
	And SF1.D_E_L_E_T_ = ''

	-- NF Entrada Itens 
	Left Join SD1010 SD1
	On D1_FILIAL = F1_FILIAL
	And D1_FORNECE = F1_FORNECE
	And D1_LOJA = F1_LOJA
	And D1_DOC = F1_DOC
	And SD1.D_E_L_E_T_ = ''

	--TES
	Left Join SF4010 SF4
	On F4_CODIGO = D1_TES
	And SF4.D_E_L_E_T_ = ''

	-- Genericas
	Left Join SX5010 SX5F1
	On SX5F1.X5_TABELA = '42'
	And SX5F1.X5_FILIAL = F1_FILIAL
	And SX5F1.X5_CHAVE = F1_ESPECIE
	And SX5F1.D_E_L_E_T_ = ''

	-- Genericas 
	Left Join SX5010 SX5E2
	On SX5E2.X5_TABELA = '05'
	And SX5E2.X5_FILIAL = E2_FILIAL
	And SX5E2.X5_CHAVE = E2_TIPO
	And SX5E2.D_E_L_E_T_ = ''

	-- Caixa
	Left Join SZM010 SZM
	On ZM_FILIAL = E2_FILIAL
	And ZM_FORNEC = E2_FORNECE
	And ZM_LOJA = E2_LOJA
	And ZM_NUMERO = E2_NUM
	And ZM_PREFIXO = E2_PREFIXO
	And ZM_PARCELA = E2_PARCELA
	And ZM_TIPO = E2_TIPO
	And SZM.D_E_L_E_T_ = ''

	Left Join SB1010 SB1 --Produtos 
	On B1_COD = D1_COD
	And SB1.D_E_L_E_T_ = ''

Where E2_FILIAL In ('01','02','03')
--And E2_TIPO In ('ISS','TX','IRF')
And E2_FORNECE In ('VOP648','MUNIC','UNIAO')
And E2_EMISSAO Between ('20240101') and ('20240131')
And E2_NUM In ('208')
and SE2.D_E_L_E_T_ = ''
Order By 7,9

--Parametros
Select X6_FIL,X6_VAR,X6_DESCRIC,X6_DESC1,X6_DESC2,X6_CONTEUD,* From SX6010
Where X6_VAR In ('MV_BX10925','MV_RT10925')
and D_E_L_E_T_ = ''


--Genericas 
Select * From SX5010 SX5
Where   X5_TABELA In ('05','42') and X5_FILIAL = '01'
and D_E_L_E_T_ = ''
Order By X5_CHAVE




--ZM_PREFIXO+SZM->ZM_NUMERO+SZM->ZM_PARCELA+SZM->ZM_TIPO+SZM->ZM_FORNEC+SZM->ZM_LOJA,.

-- Contas a Pagar 
Select * From SE2010

--SEA - Titulos Enviados ao Banco
Select * From SEA010

--SEV - Multiplas Naturezas por Titulo
Select * From SEV010

--SED - Naturezas
Select * From SED010

--FOLHA PAGAMENTO FINANCEIRA    
Select * From SZT010

-- Tabelas
Select * From SX2010
Where X2_CHAVE = 'SZM'

-- Genericas 
Select * From SX5010
Where X5_TABELA = '05'

Select Distinct ZM_TIPO From SZM010
Order By 1 