SELECT ZBE_FILIAL, ZBE_EQUIPA, H1_DESCRI, ZBE_ANO, ZBE_MES, ZBE_DIA, ZBE_DESDIA, ZBE_HORA, ZBE_OBSERV FROM ZBE010
INNER JOIN SH1010 ON H1_CODIGO=ZBE_EQUIPA
WHERE ZBE010.D_E_L_E_T_=''
ORDER BY ZBE_FILIAL, ZBE_ANO, ZBE_MES, ZBE_DIA