-- Relatório de Estrutura de produtos com componentes relacionados
SELECT PRD.B1_DESC DESCR_PRODUZIDO, COMP.B1_DESC DESCR_COMPONENTE, SG1010.*
FROM SG1010
INNER JOIN SB1010 PRD ON G1_COD=PRD.B1_COD AND PRD.D_E_L_E_T_=''
INNER JOIN SB1010 COMP ON G1_COMP=COMP.B1_COD AND COMP.D_E_L_E_T_=''
WHERE G1_FILIAL NOT IN ('XX99')
AND SG1010.D_E_L_E_T_=''
ORDER BY G1_FILIAL, G1_COD, G1_COMP