--Update
--ALTERAR STATUS
--Status de EMBARCADO para CAMBIO CONTRATADO
-- EEC - Easy Export Control


--EEC - Embarque
SELECT EEC_STATUS, EEC_STTDES, * FROM EEC010 
WHERE EEC_FILIAL='DB01' AND EEC_PREEMB IN ('1372/22','1375/22','1386/22')

--UPDATE EEC010 SET EEC_STATUS='A', EEC_STTDES='Cambio Contratado'   WHERE EEC_FILIAL='DB01' AND EEC_PREEMB IN ('1372/22','1375/22','1386/22')


--EEC - Embarque -- consulta count 
SELECT Count (EEC_STATUS) Total_Status, EEC_STATUS, Count (EEC_STTDES) Total_Desc, EEC_STTDES FROM EEC010 
Group By EEC_STATUS, EEC_STTDES
Order By 1
