SELECT 
A4_NOME TRANSPORTADORA,
A2_NOME EXPORTADOR,
EEC_ZZDTRR DATA_CARREGAMENTO,
EEC_ZZHRRR HORA_CARREGAMENTO,
EEC_ZZFDES DESTINO,
EEC_EMBARC NAVIO,
EEC_ETD ETD,
EEC_ZZDTDR DATA_DRAFT,
EEC_ZZHRDR HORA_DRAFT,
EEC_ZZDTCA DATA_CARGA,
EEC_ZZHRCA HORA_CARGA,
EEC_ZZARMA AGENTE,
EEC_ZZBOOK RESERVA,
 CASE WHEN EEC_ZZCN20<>0 THEN EEC_ZZCN20
      WHEN EEC_ZZCN40<>0 THEN EEC_ZZCN40
	  WHEN EEC_ZZ40HC<>0 THEN EEC_ZZ40HC
	  WHEN EEC_ZZCNTK<>0 THEN EEC_ZZCNTK
	  ELSE ''   END 'QTDE_EQUIPAMENTO',
 CASE WHEN EEC_ZZCN20<>0 THEN '20 DRY'
      WHEN EEC_ZZCN40<>0 THEN '40 DRY'
	  WHEN EEC_ZZ40HC<>0 THEN '40 HC'
	  WHEN EEC_ZZCNTK<>0 THEN 'TANK'
	  ELSE ''   END 'TIPO_EQUIPAMENTO',
EEC_ZZLCRT  'LOCAL DE RETIRADA',
EEC_ZZDTRT 'DATA RETIRADA',
EEC_ZZLCEN 'LOCAL DE ENTREGA',
EE8_ZZQTDP '# DE PALLETS',
SUM(EE9_QTDEM1) QUANTIDADE,
EE5_DESC EMBALAGEM,
YP_TEXTO AS DESCRICAO,
SUM(EE9_SLDINI) PESO_LIQUIDO,
EE9_PSBRTO PESO_BRUTO,
ISNULL(CAST(CAST(EEC_ZZOBSF AS VARBINARY(8000)) AS VARCHAR(8000)),'') AS OBSERVACAO
FROM EEC010
INNER JOIN EE9010 ON EE9_FILIAL=EEC_FILIAL AND EE9_PREEMB=EEC_PREEMB AND EEC010.D_E_L_E_T_=''
INNER JOIN SA2010 ON EEC_FORN=A2_COD AND EEC_FOLOJA=A2_LOJA AND SA2010.D_E_L_E_T_=''
INNER JOIN EE7010 ON EE7_FILIAL=EE9_FILIAL AND EE7_PEDIDO=EE9_PEDIDO AND EE7010.D_E_L_E_T_=''
INNER JOIN EE8010 ON EE8_FILIAL=EE7_FILIAL AND EE8_PEDIDO=EE9_PEDIDO AND EE9010.D_E_L_E_T_=''
INNER JOIN SA4010 ON A4_COD=EE7_ZZCODT AND SA4010.D_E_L_E_T_=''
INNER JOIN EE5010 ON EE5_CODEMB=EE9_EMBAL1 AND EE5010.D_E_L_E_T_=''
LEFT JOIN SYP010 ON YP_CAMPO='EE9_DESC'  AND YP_CHAVE=EE9_DESC AND SYP010.D_E_L_E_T_=''
WHERE EEC_FILIAL='BA01'
AND EEC_PREEMB='22/260-SC'
GROUP BY A4_NOME, A2_NOME,EEC_ZZDTRR,EEC_ZZHRRR,EEC_ZZFDES,EEC_EMBARC,EEC_ETD,EEC_ZZDTDR,EEC_ZZHRDR,EEC_ZZDTCA,EEC_ZZHRCA,
EEC_ZZARMA,EEC_ZZBOOK,EEC_ZZCN20,EEC_ZZCN40,EEC_ZZ40HC,EEC_ZZCNTK,EEC_ZZLCRT,EEC_ZZDTRT,EEC_ZZLCEN,EE8_ZZQTDP,EE5_DESC,
YP_TEXTO,EE9_PSBRTO,EEC_ZZOBSF


