Declare @DATAINI DATE,@DATAFIM DATE, @FILINI Char(4), @FILFIM Char(4)
Set @DATAINI = '20220701'
Set @DATAFIM = '20220731'
Set @FILINI = 'BA02'
Set @FILFIM = 'BA02'

SELECT 

CLIENTE,
LOJA,
CNPJ,
NOMECLIENTE,
DT_EMIS_PEDIDO,
COD_TPT,
TRANSP_PRINCIPAL,
COD_REDESP,
TRANSP_REDESPACHO,
CEP_ENTREGA,
LOGRADOURO_ENTREGA,
BAIRRO_ENTREGA,
CIDADE_ENTREGA,
ESTADO_ENTREGA,
PESO_BRUTO,
COD_TIPO_VEICULO,
DESC_TIPO_VEICULO,
COD_TIPO_OPERACAO,
DESCR_TIPO_OPERACAO,
FILIAL,
PEDIDO,
OBS_EXP_1,
OBS_EXP_2,
ONU,
NFE,
EMISSAO_NFE,
SUM(VALOR_MERCADORIA) VALOR_MERCADORIA,
TIPO_DE_EMBALAGEM,
TIPO_DE_FRETE,
MERCADO,
REF_EXP_ME
FROM (

SELECT 
C5_CLIENTE CLIENTE,
C5_LOJACLI LOJA,
A1_CGC CNPJ,
A1_NOME NOMECLIENTE,
CONVERT(DATE,C5_EMISSAO,12) DT_EMIS_PEDIDO,
C5_TRANSP COD_TPT,
TRANSP.A4_NOME TRANSP_PRINCIPAL,
C5_REDESP COD_REDESP,
REDESP.A4_NOME TRANSP_REDESPACHO,
CASE WHEN C5_REDESP ='' THEN A1_CEP ELSE REDESP.A4_CEP END CEP_ENTREGA,
CASE WHEN C5_REDESP ='' THEN A1_END ELSE REDESP.A4_END END LOGRADOURO_ENTREGA,
CASE WHEN C5_REDESP ='' THEN A1_BAIRRO ELSE REDESP.A4_BAIRRO END BAIRRO_ENTREGA,
CASE WHEN C5_REDESP ='' THEN A1_MUN ELSE REDESP.A4_MUN END CIDADE_ENTREGA,
CASE WHEN C5_REDESP ='' THEN A1_EST ELSE REDESP.A4_EST END ESTADO_ENTREGA,
F2_PBRUTO PESO_BRUTO,
F2_ZTPVEI COD_TIPO_VEICULO,
DUT_DESCRI DESC_TIPO_VEICULO,
F2_ZTPOPE COD_TIPO_OPERACAO,
GV4_DSTPOP DESCR_TIPO_OPERACAO,
C5_FILIAL FILIAL,
C5_NUM PEDIDO,
C5_ZZOBS1 OBS_EXP_1,
C5_ZZOBS2 OBS_EXP_2,
(SELECT CONVERT(VARCHAR,
       stuff ((SELECT ' - ' + B5_ONU
                 from SB5010 as SB5
                 where B5_COD IN (SELECT C6_PRODUTO FROM SC6010 SC62 WHERE  SC62.C6_FILIAL = SC6.C6_FILIAL AND SC62.C6_NUM = SC6.C6_NUM AND SC62.D_E_L_E_T_ = '' AND B5_ONU<>'' GROUP BY SC62.C6_PRODUTO)
                 for xml path('')),
              1, 2, ''))) as ONU,
F2_DOC NFE,
CONVERT(DATE,F2_EMISSAO,12) EMISSAO_NFE,
SC6.C6_VALOR VALOR_MERCADORIA,
F2_ESPECI1 TIPO_DE_EMBALAGEM,
C5_TPFRETE TIPO_DE_FRETE,
CASE WHEN C5_TIPOCLI='X' THEN 'EXTERNO' ELSE 'INTERNO' END MERCADO,
F2_HAWB REF_EXP_ME
FROM SC5010
INNER JOIN SA1010 ON A1_COD=C5_CLIENTE AND A1_LOJA=C5_LOJACLI AND SA1010.D_E_L_E_T_=''
LEFT JOIN SA4010 TRANSP ON TRANSP.A4_COD=C5_TRANSP AND TRANSP.D_E_L_E_T_=''
LEFT JOIN SA4010 REDESP ON REDESP.A4_COD=C5_REDESP AND REDESP.D_E_L_E_T_=''
LEFT JOIN SF2010 ON F2_FILIAL=C5_FILIAL AND F2_DOC=C5_NOTA AND SF2010.D_E_L_E_T_=''
LEFT JOIN DUT010 ON DUT_TIPVEI=F2_ZTPVEI AND DUT010.D_E_L_E_T_=''
LEFT JOIN GV4010 ON GV4_CDTPOP=F2_ZTPOPE AND GV4010.D_E_L_E_T_=''
INNER JOIN SC6010 SC6 ON SC6.C6_FILIAL=C5_FILIAL AND SC6.C6_NUM=C5_NUM AND SC6.D_E_L_E_T_=''
LEFT JOIN SB5010 ON B5_COD=SC6.C6_PRODUTO AND SB5010.D_E_L_E_T_=''
WHERE C5_FILIAL BETWEEN @FILINI AND @FILFIM AND C5_EMISSAO BETWEEN @DATAINI AND @DATAFIM

AND SC5010.D_E_L_E_T_=''
)TMP
GROUP BY 
CLIENTE,
DT_EMIS_PEDIDO,
LOJA,
CNPJ,
NOMECLIENTE,
COD_TPT,
TRANSP_PRINCIPAL,
COD_REDESP,
TRANSP_REDESPACHO,
CEP_ENTREGA,
LOGRADOURO_ENTREGA,
BAIRRO_ENTREGA,
CIDADE_ENTREGA,
ESTADO_ENTREGA,
PESO_BRUTO,
COD_TIPO_VEICULO,
DESC_TIPO_VEICULO,
COD_TIPO_OPERACAO,
DESCR_TIPO_OPERACAO,
FILIAL,
PEDIDO,
OBS_EXP_1,
OBS_EXP_2,
ONU,
NFE,
EMISSAO_NFE,
TIPO_DE_EMBALAGEM,
TIPO_DE_FRETE,
MERCADO,
REF_EXP_ME
ORDER BY
FILIAL,
PEDIDO