
Declare @FILIAL Char(4), @FROTA Char(10), @DATAINI Date, @DATAFIM Date

Set @FILIAL = 'FK01'
Set  @FROTA = 'C-148'
Set  @DATAINI = '20220101'
Set @DATAFIM = '20220801'


SELECT D1_FILIAL FILIAL, D1_CC CCUSTO, CTT_DESC01 DESCR_CCUSTO, D1_ZZFROT FROTA, ZN_PLACA PLACA, ZN_MODELO MODELO, D1_COD CODIGO, B1_DESC DESCRICAO, D1_UM UM, D1_QUANT QUANT, D1_VUNIT VLR_UNIT, D1_TOTAL VLR_TOTAL , D1_DTDIGIT, D1_FORNECE, A2_CGC, A2_NOME, A2_LOJA
FROM SD1010 D1
INNER JOIN CTT010 CTT ON CTT_CUSTO=D1_CC AND CTT_FILIAL=D1_FILIAL AND CTT.D_E_L_E_T_='' 
INNER JOIN SZN010 SZN ON ZN_FROTA=D1_ZZFROT AND SZN.D_E_L_E_T_='' 
INNER JOIN SB1010 SB1 ON B1_COD=D1_COD AND SB1.D_E_L_E_T_='' 
INNER JOIN SA2010 SA2 ON A2_COD = D1_FORNECE AND A2_LOJA = D1_LOJA AND SA2.D_E_L_E_T_ =''
WHERE D1.D1_FILIAL In (@FILIAL)
AND D1_ZZFROT = @FROTA
AND D1_DTDIGIT BETWEEN @DATAINI AND @DATAFIM AND D1.D_E_L_E_T_='' 