SELECT 'P' PREVREAL, 'R' RECPAG, E1_FILIAL FILIAL, E1_PREFIXO PREFIXO, E1_NUM NUM, E1_PARCELA PARCELA, E1_MOEDA MOEDA, 
 E1_TIPO TIPO, E1_NATUREZ NATUREZ, E1_PORTADO PORTADO, E1_AGEDEP AGEDEP, E1_CONTA CONTA, 
 E1_CLIENTE CLIFOR, E1_LOJA LOJA, E1_NOMCLI NOME, E1_EMISSAO EMISSAO, E1_VENCTO VENCTO, E1_VENCREA VENCREA, E1_VALOR VALOR, 
 ( (E1_SALDO+E1_SDACRES-E1_SDDECRE) * CASE WHEN ( E1_TIPO IN ('AB-','CF-','CS-','FB-','FC-','FE-','FM-','FP-','FU-','I2-','IM-','IN-','IR-','IS-','MN-','PI-','FC-','FE-') OR E1_TIPO IN ('NCC','NDF|DIC') ) THEN -1 ELSE 1 END) SALDO, 
 ' ' TIPODOC, E1_SDACRES SDACRES, E1_SDDECRE SDDECRE, R_E_C_N_O_ RECNO 
 FROM SE1010 
 WHERE E1_FILIAL = '  ' 
 AND E1_VENCREA >= '20220312' AND E1_VENCREA <= '20220603' 
 AND E1_TIPO <> 'BOL' 
 AND ( (E1_TIPO <> 'NCC') OR (E1_TIPO = 'NCC' AND E1_PREFIXO = 'DPC') ) 
 AND E1_SALDO > 0 
 AND E1_FLUXO <> 'N' 
 AND D_E_L_E_T_ = ' ' 
 UNION ALL 
 SELECT 'P' PREVREAL, 'P' RECPAG, E2_FILIAL FILIAL, E2_PREFIXO PREFIXO, E2_NUM NUM, E2_PARCELA PARCELA, E2_MOEDA MOEDA, 
 E2_TIPO TIPO, E2_NATUREZ NATUREZ, E2_PORTADO PORTADO, ' ' AGEDEP, ' ' CONTA, 
 E2_FORNECE CLIFOR, E2_LOJA LOJA, E2_NOMFOR NOME, E2_EMISSAO EMISSAO, E2_VENCTO VENCTO, E2_VENCREA VENCREA, E2_VALOR VALOR, 
 ( (E2_SALDO+E2_SDACRES-E2_SDDECRE) * CASE WHEN ( E2_TIPO IN ('AB-','CF-','CS-','FB-','FC-','FE-','FM-','FP-','FU-','I2-','IM-','IN-','IR-','IS-','MN-','PI-','FC-','FE-') OR E2_TIPO IN ('NCC','NDF|DIC') ) THEN -1 ELSE 1 END) SALDO, 
 ' ' TIPODOC, E2_SDACRES SDACRES, E2_SDDECRE SDDECRE, R_E_C_N_O_ RECNO 
 FROM SE2010 
 WHERE E2_FILIAL = '  ' 
 AND E2_VENCREA >= '20220312' AND E2_VENCREA <= '20220603' 
 AND E2_TIPO NOT IN ('NCC') 
 AND E2_SALDO > 0 
 AND E2_FLUXO <> 'N' 
 AND E2_TIPO NOT IN ('PR') 
 AND D_E_L_E_T_ = ' ' 
 ORDER BY VENCREA