SELECT ZZX_FILIAL FILIAL, ZZX_CODIGO CODIGO_BUDGET, ZZX_CODRES COD_RESPONSAVEL, ZZU_NOMRES NOME_RESPONSAVEL, ZZX_SEQUEN SEQUENCIA, ZZV_CODUSR COD_USUARIO, ZZV_NOMUSR NOME_USUARIO, ZZX_CUSTDE CENTRO_CUSTO_DE, ZZX_CUSTAT CENTRO_CUSTO_ATE, ZZX_CONTDE CONTA_CTB_DE, ZZX_CONTAT CONTA_CTB_ATE,CASE WHEN ZZV_CTASAL='2' THEN 'SIM' ELSE 'NAO' END ACESSO_CTA_SALARIO FROM ZZX010

INNER JOIN ZZV010 ON ZZV_FILIAL=ZZX_FILIAL AND ZZV_CODIGO=ZZX_CODIGO AND ZZV_CODRES=ZZX_CODRES AND ZZV_SEQUEN=ZZX_SEQUEN AND ZZV010.D_E_L_E_T_=''

INNER JOIN ZZU010 ON ZZU_FILIAL=ZZX_FILIAL AND ZZU_CODIGO=ZZX_CODIGO AND ZZU_CODRES=ZZX_CODRES AND ZZU010.D_E_L_E_T_=''

WHERE ZZX010.D_E_L_E_T_=''

ORDER BY 1,2,3,5,6,8,10

