SELECT 
	SDC.DC_FILIAL							AS FILIAL_EMPENHO, 
	SDC.DC_PRODUTO							AS COD_PROD_EMPENHADO,  
	SDC.DC_LOCALIZ							AS ACONDICIONAMENTO, 
	DC_QUANT								AS QUANTIDADE_EMPENHADA, 
	CAST(ZP4.ZP4_DATA AS DATE)				AS DATA_RESERVA,
	ZP4.ZP4_CODIGO							AS NUMERO_RESERVA_PORTAL,
	CASE
			WHEN ZP4.ZP4_STATUS = '1'
				THEN 'AGUARDANDO'
			WHEN ZP4.ZP4_STATUS = '2'
				THEN 'CONFIRMADA'
			WHEN ZP4.ZP4_STATUS = '3'
				THEN 'EXPIRADA'
			WHEN ZP4.ZP4_STATUS= '4'
				THEN 'CANCELADA'
			ELSE 'N/I'
	END										AS STATUS_RESERVA,
	ZP4.ZP4_CODCLI + '-' + ZP4.ZP4_LOJCLI	AS CODIGO_LOJA_CLIENTE,
	ISNULL(ZP6.ZP6_NUM,'NÃO')				AS PEDIDO_PORTAL,
	
	CASE
			WHEN ZP5.ZP5_NUM IS NULL
				THEN 'NÃO'
			ELSE 
				CASE
					WHEN ZP5.ZP5_STATUS = '0'
						THEN 'REVISÃO'
					WHEN ZP5.ZP5_STATUS = '1'
						THEN 'MANUTENÇÃO'
					WHEN ZP5.ZP5_STATUS = '2'
						THEN 'AGUARDANDO APROVAÇÃO'
					WHEN ZP5.ZP5_STATUS = '3'
						THEN 'EM APROVAÇÃO'
					WHEN ZP5.ZP5_STATUS = '4'
						THEN 'AGUARDANDO CONFIRMAÇÃO'
					WHEN ZP5.ZP5_STATUS = '5'
						THEN 'CONFIRMADO'
					WHEN ZP5.ZP5_STATUS = '6'
						THEN 'NÃO APROVADO'
					WHEN ZP5.ZP5_STATUS = '7'
						THEN 'CANCELADO'
					WHEN ZP5.ZP5_STATUS = '8'
						THEN 'APROVAÇÃO TECNICA'
					WHEN ZP5.ZP5_STATUS = '9'
						THEN 'AGUARDANDO PROCESSAMENTO'
					WHEN ZP5.ZP5_STATUS = 'A'
						THEN 'EM PROCESSAMENTO'
					WHEN ZP5.ZP5_STATUS = 'B'
						THEN 'ERRO PROCESSAMENTO'
				END
	END										AS STATUS_PEDIDO_PORTAL,
	
	
	ISNULL(SC6.C6_NUM, 'NÃO')				AS PEDIDO_INTERNO,
	CASE
		WHEN SC5.C5_NUM IS NULL
			THEN 'NÃO'
		ELSE
			CASE
				WHEN SC5.C5_LIBEROK = 'E' OR SC5.C5_NOTA <> '' OR SC6.C6_BLQ = 'R ' OR SC6.C6_QTDENT >= SC6.C6_QTDVEN
					THEN 'ENCER./CANC./BLOQ.'
				ELSE 'EM ABERTO'
			END											
	END										AS STATUS_PEDIDO_INTERNO,

	CASE
		WHEN SC5.C5_NUM IS NULL
			THEN 'NÃO'
		ELSE
			CASE
				WHEN SC5.C5_DTLICRE <> ''
					THEN 'LIB. CRED.'
				ELSE 'BLOQ. CRED'
			END											
	END										AS STATUS_PEDIDO_INTERNO



FROM SDC010 SDC WITH(NOLOCK)

LEFT JOIN ZP4010 ZP4 WITH(NOLOCK)
	ON SDC.DC_FILIAL  = ZP4.ZP4_FILIAL
	AND SDC.DC_PEDIDO = ZP4.ZP4_CODIGO
	AND SDC.D_E_L_E_T_ = ZP4.D_E_L_E_T_ 

LEFT JOIN ZP6010 ZP6 WITH(NOLOCK)
	ON  ZP6.ZP6_FILIAL IN ('','01','02')
	AND ZP4.ZP4_CODIGO = ZP6.ZP6_NUMRES
	AND ZP4.D_E_L_E_T_ = ZP6.D_E_L_E_T_

LEFT JOIN ZP5010 ZP5 WITH(NOLOCK)
	ON  ZP5.ZP5_FILIAL IN ('','01','02') 
	AND ZP6.ZP6_NUM = ZP5.ZP5_NUM
	AND ZP6.D_E_L_E_T_ = ZP5.D_E_L_E_T_

LEFT JOIN SC6010 SC6 WITH(NOLOCK)
	ON  SC6.C6_FILIAL IN ('','01','02')
	AND ZP6.ZP6_NUMRES = SC6.C6_ZZNRRES
	AND ZP6.D_E_L_E_T_ = SC6.D_E_L_E_T_

LEFT JOIN SC5010 SC5 WITH(NOLOCK)
	ON  SC6.C6_FILIAL	= SC5.C5_FILIAL
	AND SC6.C6_NUM		= SC5.C5_NUM
	AND SC6.D_E_L_E_T_  = SC5.D_E_L_E_T_


WHERE SDC.DC_ORIGEM = 'ZP4'
--And  ZP4_CODIGO In ('006356','006357')
AND SDC.D_E_L_E_T_ <> '*'
Order By 6



--RESERVAS DE PRODUTOS          
--Select * From SZZ010
--SZZ_STATUS 0=Em Aberto;1=Empenhada;2=Fat.Parcial;3=Fat.Total;9=Cancelada                                                                   

/*

--SDC - Composicao do Empenho
Select DC_ORIGEM,* From SDC010
Where DC_ORIGEM In ('ZP4','SC6')
And DC_PRODUTO  In ('1150905401')
And DC_PEDIDO In ('023274','429769')
And D_E_L_E_T_ = ''
Order By DC_ITEM

--SBF - Saldos por Endereco
Select * From SBF010
Where BF_FILIAL = '01' and BF_PRODUTO In ('1150905401')
and BF_QUANT > 0 and BF_EMPENHO > 0
And D_E_L_E_T_ ='' and BF_LOCALIZ In ('R00200','R00100')         

--RESERVAS PORTAL COBRECOM      
Select * From ZP4010
Where ZP4_CODIGO In ('023274')
--Or  ZP4_STATUS In ('1')
And D_E_L_E_T_ = ''
--And ZP4_CODPRO = '1540504401'
--And ZP4_DATA >= '20240701'
Order By ZP4_STATUS
--ZP4_STATUS - 1=Pendente;2=Atendida;3=Expirada;4=Cancelada   

--PV
Select C6_NUM,C6_ZZNRRES,* From SC6010
Where C6_ZZNRRES = '023274'
And D_E_L_E_T_ = ''

*/
