/*----SDC - Composicao do Empenho
SELECT *
FROM SDC010
WHERE DC_FILIAL = '02'
AND DC_PRODUTO = '1141102401'
AND DC_LOCALIZ  ='B00500'
AND D_E_L_E_T_ = ''

----SBF - Saldos por Endereco
SELECT *
FROM SBF010
WHERE BF_FILIAL = '02'
AND BF_PRODUTO  ='1141102401'
AND BF_LOCALIZ = 'B00500'
AND D_E_L_E_T_  =''
*/

----SBF - Saldos por Endereco x SDC - Composicao do Empenho - Ajustes
SELECT BF_FILIAL, BF_PRODUTO, BF_LOCAL, BF_LOCALIZ, BF_QUANT, BF_EMPENHO, 
--update SBF010 set BF_EMPENHO = 
		(SELECT ISNULL(SUM(DC.DC_QUANT),0) QTDDC
		FROM SDC010 DC  With(Nolock)
		WHERE BF_FILIAL = DC_FILIAL
		AND BF_PRODUTO = DC_PRODUTO
		AND BF_LOCAL = DC_LOCAL
		AND BF_LOCALIZ = DC_LOCALIZ
		AND BF.D_E_L_E_T_ = DC.D_E_L_E_T_) As DC_QUANT
FROM SBF010 BF With(Nolock)
WHERE BF_FILIAL IN ('01','02')
AND BF_EMPENHO <> 
		(SELECT ISNULL(SUM(DC_E.DC_QUANT),0) QTDDC
		FROM SDC010 DC_E  With(Nolock)
		WHERE BF_FILIAL = DC_FILIAL
		AND BF_PRODUTO = DC_PRODUTO
		AND BF_LOCAL = DC_LOCAL
		AND BF_LOCALIZ = DC_LOCALIZ
		AND BF.D_E_L_E_T_ = DC_E.D_E_L_E_T_)
AND BF.D_E_L_E_T_ = ''
Order By 2

