-- Script Analise Pedido de Venda x Estoque 
-- Lance Minimo  menor que Qtde Atual

Declare @FILIAL VARCHAR(2), @BFLOCAL Varchar(2), @CODPRODINI Varchar(10), @CODPRODFIM Varchar(10)
SET @FILIAL = '01'
Set @BFLOCAL = '01'
Set @CODPRODINI = '0000000000'
SET @CODPRODFIM = '999999999'

Select * FROM 
			(SELECT BF_LOCAL, BF_PRODUTO, Isnull(BF_QUANT-BF_EMPENHO,0) TOTAL, 
				SUBSTRING(BF_LOCALIZ,1,1) ACONDIC     , ISNULL(CAST( isnull(SUBSTRING(BF_LOCALIZ,2,5),'1') AS NUMERIC ),0) LANCE, 
				ISNULL(( isnull(SUBSTRING(BF_LOCALIZ,2,5),'1') ),'') METRAG_S, 'E' SD_ORIG
				From SBF010 BF 
				Where BF.D_E_L_E_T_ = ' ' AND BF_FILIAL = @FILIAL and BF_LOCAL = @BFLOCAL and (BF_QUANT-BF_EMPENHO) > 0  
				and SUBSTRING(BF_LOCALIZ,1,1) <> 'B'  and BF_PRODUTO Between @CODPRODINI and @CODPRODFIM
				AND CAST(isnull(BF_QUANT-BF_EMPENHO,0) /  CAST(SUBSTRING(BF_LOCALIZ,2,5) AS NUMERIC) AS INT) = 0
				
				UNION  SELECT @BFLOCAL AS BF_LOCAL, 
				ZZE_PRODUT AS BF_PRODUTO, ZZE_TOTSA AS TOTAL, ZZE_ACONDS AS ACONDIC, ZZE_TOTSA AS LANCE, 
				'X' METRAG_S, (ZZE_FILIAL + ZZE_ID) AS SD_ORIG    
				From ZZE010 ZZE  
				Where ZZE.D_E_L_E_T_ = ' ' 
				AND CAST(isnull(ZZE_TOTSA,0)as Int) / CAST(isnull(ZZE_METRAS,0)As Int) = 0
				And ZZE_TOTSA <> 0 And ZZE_METRAS <> 0
								
				AND ZZE_FILIAL = @FILIAL and ZZE_DEVTOT = 0 AND ZZE_STATUS != '9'  and ZZE_PEDIDO = '000001' AND ZZE_ACONDS <> 'S'  
				AND ZZE_SITUAC <> '1' and ZZE_PRODUT Between @CODPRODINI and @CODPRODFIM  ) AS T 
				WHERE SUBSTRING(T.BF_PRODUTO,1,5) 
				NOT IN ( Select SUBSTRING(ZZD_COD,1,5) 

				
				FROM ZZD010 ZZD 
				WHERE  ZZD_FILIAL = @FILIAL AND ZZD.D_E_L_E_T_ = ' '  
				AND ( T.ACONDIC = ZZD_ACONDI AND T.METRAG_S = ZZD_METRAG AND SUBSTRING(T.BF_PRODUTO,1,5) = SUBSTRING(ZZD_COD,1,5) )  ) 
Order By BF_PRODUTO

