-- Mapeamento TSS x PV Itens 
-- SPED050 TSS x SC6
-- Analise XML nItemPed x C6_ITPDCLI - Máximo 06 Casas 
--I05. Produtos e Serviços / Pedido de Compra
--# ID Campo Descrição Ele Pai Tipo Ocor. Tam. Observação
--128m I60 xPed Número do Pedido de Compra E I01 C 0-1 1-15 Informação de interesse do emissor para controle do B2B.
--(v2.0)
--28n I61 nItemPed Item do Pedido de Compra E I01 N 0-1 6

SELECT 
    CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP)) AS [XML_ERP],
    CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG)) AS [XML_SIG],
    CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS)) AS [XML_TSS],

	C6_CLI,C6_LOJA,A1_NOME,
    '0' + SUBSTRING(NFE_ID, 1, 1) AS TSS_FILIAL,
    SUBSTRING(NFE_ID, 4, 13) AS TSS_NF,
    C6_FILIAL, C6_NOTA,
    C6_PEDCLI, C6_ITPDCLI, C6_PEDCOM, C6_ITEMPC,

    CASE
        WHEN CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP))) > 0 AND
             CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP))) > CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP)))
        THEN SUBSTRING(
            CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP)),
            CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP))) + 10,
            CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP))) - CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_ERP))) - 10
        )
        ELSE NULL
    END AS nItemPed_ERP,

    CASE
        WHEN CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG))) > 0 AND
             CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG))) > CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG)))
        THEN SUBSTRING(
            CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG)),
            CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG))) + 10,
            CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG))) - CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_SIG))) - 10
        )
        ELSE NULL
    END AS nItemPed_SIG,

    CASE
        WHEN CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) > 0 AND
             CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) > CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS)))
        THEN SUBSTRING(
            CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS)),
            CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) + 10,
            CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) - CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) - 10
        )
        ELSE NULL
    END AS nItemPed_TSS

FROM 
    SPED050

Inner JOIN IFC_P12.dbo.SC6010 SC6
    ON '0' + SUBSTRING(NFE_ID, 1, 1) COLLATE Latin1_General_BIN = C6_FILIAL COLLATE Latin1_General_BIN
    AND SUBSTRING(NFE_ID, 4, 13) COLLATE Latin1_General_BIN = C6_NOTA COLLATE Latin1_General_BIN
    AND (CASE
            WHEN CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) > 0 AND
                 CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) > CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS)))
            THEN SUBSTRING(
                CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS)),
                CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) + 10,
                CHARINDEX('</nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) - CHARINDEX('<nItemPed>', CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), XML_TSS))) - 10
            )
            ELSE NULL
        END) = C6_ITPDCLI COLLATE Latin1_General_BIN
    AND SC6.D_E_L_E_T_ = ''

Inner Join	IFC_P12.dbo.SA1010 SA1
	On SC6.C6_CLI = A1_COD 
	And C6_LOJA = A1_LOJA
	And SC6.D_E_L_E_T_ = ''

WHERE 
    C6_CLI IN ('006264', '002083') 
    AND C6_ITPDCLI <> '' 
    AND C6_PEDCLI <> '' 
    AND C6_NOTA <> ''
    AND DATE_NFE >= '20230101' 
    AND SPED050.D_E_L_E_T_ = '';
