O

/****** Object:  View [dbo].[BI_VW_NOTAENTRADA]    Script Date: 15/03/2024 14:21:08 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--ALTER VIEW [dbo].[BI_VW_NOTAENTRADA]
--AS

SELECT 
	D1.D1_FILIAL				AS Filial,
	D1.D1_DOC					AS NotaFiscal,
	D1.D1_ITEM					AS ItemNota,
	D1.D1_PEDIDO				AS PedidoCompra,
	D1.D1_ITEM					AS ItemPedidoCompra,
	D1.D1_EMISSAO				AS EmissaoNota,
	D1.D1_DTDIGIT				AS DataEntradaSistema,
	ISNULL(E4.E4_CODIGO,'')		AS CodCondPag,
	ISNULL(E4.E4_DESCRI,'')		AS DescCondPag,
	ISNULL(E4.E4_ZMEDPAG,0)		AS MedCondPag,
	RTRIM(LTRIM(B1.B1_COD))		AS CodProduto,
	RTRIM(LTRIM(B1.B1_DESC))	AS Produto,
	RTRIM(LTRIM(B1.B1_GRUPO))	AS GrupoProduto,
	D1.D1_QUANT					AS Quantidade,
	D1.D1_UM					AS UnidadeMedida,
	D1.D1_VUNIT					AS Preco,
	D1.D1_TOTAL					AS Total,
	D1.D1_VALICM				AS Icms,
	D1.D1_VALIPI				AS Ipi

FROM SD1010 D1

INNER JOIN SB1010 B1
	ON '' = B1.B1_FILIAL
	AND D1.D1_COD = B1.B1_COD
	AND D1.D_E_L_E_T_ = B1.D_E_L_E_T_ 
INNER JOIN SA2010 A2
	ON '' = A2.A2_FILIAL
	AND D1.D1_FORNECE	= A2.A2_COD
	AND D1.D1_LOJA		= A2.A2_LOJA
	AND D1.D_E_L_E_T_	= A2.D_E_L_E_T_
INNER JOIN SF1010 F1
	ON D1.D1_FILIAL		= F1.F1_FILIAL
	AND D1.D1_DOC		= F1.F1_DOC
	AND D1.D1_FORNECE	= F1.F1_FORNECE
	AND D1.D1_LOJA		= F1.F1_LOJA
	AND D1.D_E_L_E_T_	= F1.D_E_L_E_T_
LEFT JOIN SE4010 E4
	ON ''				= E4.E4_FILIAL
	AND F1.F1_COND		= E4.E4_CODIGO
	AND F1.D_E_L_E_T_	= E4.D_E_L_E_T_
WHERE
D1.D1_EMISSAO >= '20220101'
AND F1.F1_TIPO = 'N' 
AND LEFT(A2.A2_CGC,8) NOT IN ('02544042')
AND D1.D_E_L_E_T_ = ''
GO



