-- Indicadores 

Declare @DATAINI Char(4), @DATAFIM Char(4);
Set @DATAINI = '20240701'
Set @DATAFIM = '20240731'

-- NF Saida 
Select DATEPART(MONTH, F2_EMISSAO) As MES,DATEPART(YEAR, F2_EMISSAO) As Ano,
F2_ESPECIE,X5_DESCRI,
Format(Count(F2_DOC),'#,0.0000', 'pt-BR') as NFE_QTDE, Format(Sum(F2_VALBRUT),'#,0.0000', 'pt-BR') as NFE_VALOR,
Format(Count(F2_PLIQUI),'#,0.0000', 'pt-BR') as PESO_LIQUID,Format(Count(F2_PBRUTO),'#,0.0000', 'pt-BR') as PESO_BRUTO,
	Case 
		When F2_TIPO = 'N' Then 'NF Normal'
		When F2_TIPO = 'C' Then 'Compl. Preco'
		When F2_TIPO = 'D' Then 'Devolucao'
		When F2_TIPO = 'I' Then ' NF Compl. ICMS'
		When F2_TIPO = 'P' Then 'NF Compl. IPI'
		When F2_TIPO = 'B' Then 'NF Beneficiamento'
		End as TIPO

From SF2010 SF2
	
	Inner Join SX5010 SX5
	On X5_FILIAL = F2_FILIAL
	And X5_TABELA = '42' --ESPECIES DE DOCUMENTOS FISCAIS                         
	And X5_CHAVE = F2_ESPECIE
	And SX5.D_E_L_E_T_ = ''

Where F2_EMISSAO Between (@DATAINI) and (@DATAFIM)
And SF2.D_E_L_E_T_ = ''
Group By F2_ESPECIE,F2_TIPO,X5_DESCRI,
DATEPART(MONTH, F2_EMISSAO),DATEPART(YEAR, F2_EMISSAO)
Order By NFE_VALOR Asc



-- Indicadores 
-- NF Entrada 
Select DATEPART(MONTH, F1_EMISSAO) As MES,DATEPART(YEAR, F1_EMISSAO) As Ano,
F1_ESPECIE,X5_DESCRI,
Format(Count(F1_DOC),'#,0.0000', 'pt-BR') as NFE_QTDE, Format(Sum(F1_VALBRUT),'#,0.0000', 'pt-BR') as NFE_VALOR,
	Case 
		When F1_TIPO = 'N' Then 'NF Normal'
		When F1_TIPO = 'C' Then 'Compl. Preco'
		When F1_TIPO = 'D' Then 'Devolucao'
		When F1_TIPO = 'I' Then ' NF Compl. ICMS'
		When F1_TIPO = 'P' Then 'NF Compl. IPI'
		When F1_TIPO = 'B' Then 'NF Beneficiamento'
		End as TIPO

From SF1010 SF1
	
	Inner Join SX5010 SX5
	On X5_FILIAL = F1_FILIAL
	And X5_TABELA = '42' --ESPECIES DE DOCUMENTOS FISCAIS                         
	And X5_CHAVE = F1_ESPECIE
	And SX5.D_E_L_E_T_ = ''

Where F1_EMISSAO Between (@DATAINI) and (@DATAFIM)
And SF1.D_E_L_E_T_ = ''
Group By F1_ESPECIE,F1_TIPO,X5_DESCRI,
DATEPART(MONTH, F1_EMISSAO),DATEPART(YEAR, F1_EMISSAO)
Order By NFE_VALOR Asc


-- Contas a Receber
Select E1_TIPO,X5_DESCRI,
DATEPART(MONTH, E1_VENCTO) As Mes,DATEPART(YEAR, E1_VENCTO) As ANO,
Format(Count(E1_NUM),'#,0.0000', 'pt-BR') As FIN_CAR_QTDE, Format(Sum(E1_SALDO),'#,0.0000', 'pt-BR') As FIN_CAR_VALOR
From SE1010 SE1

	--Genericas 
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = E1_FILIAL
	And X5_CHAVE = E1_TIPO
	And SX5.D_E_L_E_T_ = ''

Where E1_VENCTO Between (@DATAINI) and (@DATAFIM)
And SE1.D_E_L_E_T_ = ''
Group By E1_TIPO,X5_DESCRI,
DATEPART(MONTH, E1_VENCTO),DATEPART(YEAR, E1_VENCTO)


-- Contas a Pagar 
Select E2_TIPO,X5_DESCRI,
DATEPART(MONTH, E2_VENCTO) As Mes,DATEPART(YEAR, E2_VENCTO) As ANO,
Format(Count(E2_NUM),'#,0.0000', 'pt-BR') As FIN_CAR_QTDE, Format(Sum(E2_SALDO),'#,0.0000', 'pt-BR') As FIN_CAR_VALOR
From SE2010 SE2

	--Genericas 
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = E2_FILIAL
	And X5_CHAVE = E2_TIPO
	And SX5.D_E_L_E_T_ = ''

Where E2_VENCTO Between (@DATAINI) and (@DATAFIM)
And SE2.D_E_L_E_T_ = ''
Group By E2_TIPO,X5_DESCRI,
DATEPART(MONTH, E2_VENCTO),DATEPART(YEAR, E2_VENCTO)





Declare @DATAINI Char(10), @DATAFIM Char(10);
Set @DATAINI = '20240701'
Set @DATAFIM = '20240731'
-- NF Entrada Geral 
Select DATEPART(MONTH, F1_EMISSAO) As MES,DATEPART(YEAR, F1_EMISSAO) As Ano,
Format(Count(F1_DOC),'#,0.0000', 'pt-BR') as NFE_ENT_QTDE, Format(Sum(F1_VALBRUT),'#,0.0000', 'pt-BR') as NFE_ENT_VALOR
From SF1010 SF1
Where F1_EMISSAO Between (@DATAINI) and (@DATAFIM)
And SF1.D_E_L_E_T_ = ''
Group By DATEPART(MONTH, F1_EMISSAO),DATEPART(YEAR, F1_EMISSAO)
Order By NFE_ENT_VALOR Asc

-- NF Saida Geral 
Select DATEPART(MONTH, F2_EMISSAO) As MES,DATEPART(YEAR, F2_EMISSAO) As Ano,
Format(Count(F2_DOC),'#,0.0000', 'pt-BR') as NFE_SAI_QTDE, Format(Sum(F2_VALBRUT),'#,0.0000', 'pt-BR') as NFE_SAI_VALOR,
Format(Count(F2_PLIQUI),'#,0.0000', 'pt-BR') as NFE_SAI_PESO_LIQUID,Format(Count(F2_PBRUTO),'#,0.0000', 'pt-BR') as NFE_SAIPESO_BRUTO
From SF2010 SF1
Where F2_EMISSAO Between (@DATAINI) and (@DATAFIM)
And SF1.D_E_L_E_T_ = ''
Group By DATEPART(MONTH, F2_EMISSAO),DATEPART(YEAR, F2_EMISSAO)
Order By NFE_SAI_VALOR Asc

-- Contas a Pagar Geral 
Select 
DATEPART(MONTH, E2_VENCTO) As Mes,DATEPART(YEAR, E2_VENCTO) As ANO,
Format(Count(E2_NUM),'#,0.0000', 'pt-BR') As FIN_CAP_QTDE, Format(Sum(E2_SALDO),'#,0.0000', 'pt-BR') As FIN_CAP_VALOR
From SE2010 SE2

	--Genericas 
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = E2_FILIAL
	And X5_CHAVE = E2_TIPO
	And SX5.D_E_L_E_T_ = ''

Where E2_VENCTO Between (@DATAINI) and (@DATAFIM)
And SE2.D_E_L_E_T_ = ''
Group By DATEPART(MONTH, E2_VENCTO),DATEPART(YEAR, E2_VENCTO)

-- Contas a Receber Geral
Select 
DATEPART(MONTH, E1_VENCTO) As Mes,DATEPART(YEAR, E1_VENCTO) As ANO,
Format(Count(E1_NUM),'#,0.0000', 'pt-BR') As FIN_CAR_QTDE, Format(Sum(E1_SALDO),'#,0.0000', 'pt-BR') As FIN_CAR_VALOR
From SE1010 SE1

	--Genericas 
	Inner Join SX5010 SX5
	On  X5_TABELA = '05'
	And X5_FILIAL = E1_FILIAL
	And X5_CHAVE = E1_TIPO
	And SX5.D_E_L_E_T_ = ''

Where E1_VENCTO Between (@DATAINI) and (@DATAFIM)
And SE1.D_E_L_E_T_ = ''
Group By DATEPART(MONTH, E1_VENCTO),DATEPART(YEAR, E1_VENCTO)





DECLARE @DATAINI CHAR(10), @DATAFIM CHAR(10);
SET @DATAINI = '20240101';
SET @DATAFIM = '20241231';

-- NF Entrada Geral, NF Saida Geral, Contas a Pagar Geral, Contas a Receber Geral em uma consulta unificada
SELECT 
    'Entrada' AS Tipo,
    DATEPART(MONTH, F1_EMISSAO) AS MES,
    DATEPART(YEAR, F1_EMISSAO) AS Ano,
    FORMAT(COUNT(F1_DOC), '#,0.0000', 'pt-BR') AS QTDE,
    FORMAT(SUM(F1_VALBRUT), '#,0.0000', 'pt-BR') AS VALOR,
    NULL AS PESO_LIQUID,
    NULL AS PESO_BRUTO
FROM SF1010 SF1
WHERE F1_EMISSAO BETWEEN @DATAINI AND @DATAFIM
AND SF1.D_E_L_E_T_ = ''
GROUP BY DATEPART(MONTH, F1_EMISSAO), DATEPART(YEAR, F1_EMISSAO)

UNION ALL

SELECT 
    'Saida' AS Tipo,
    DATEPART(MONTH, F2_EMISSAO) AS MES,
    DATEPART(YEAR, F2_EMISSAO) AS Ano,
    FORMAT(COUNT(F2_DOC), '#,0.0000', 'pt-BR') AS QTDE,
    FORMAT(SUM(F2_VALBRUT), '#,0.0000', 'pt-BR') AS VALOR,
    FORMAT(SUM(F2_PLIQUI), '#,0.0000', 'pt-BR') AS PESO_LIQUID,
    FORMAT(SUM(F2_PBRUTO), '#,0.0000', 'pt-BR') AS PESO_BRUTO
FROM SF2010 SF1
WHERE F2_EMISSAO BETWEEN @DATAINI AND @DATAFIM
AND SF1.D_E_L_E_T_ = ''
GROUP BY DATEPART(MONTH, F2_EMISSAO), DATEPART(YEAR, F2_EMISSAO)

UNION ALL

SELECT 
    'Contas a Pagar' AS Tipo,
    DATEPART(MONTH, E2_VENCTO) AS MES,
    DATEPART(YEAR, E2_VENCTO) AS Ano,
    FORMAT(COUNT(E2_NUM), '#,0.0000', 'pt-BR') AS QTDE,
    FORMAT(SUM(E2_SALDO), '#,0.0000', 'pt-BR') AS VALOR,
    NULL AS PESO_LIQUID,
    NULL AS PESO_BRUTO
FROM SE2010 SE2
INNER JOIN SX5010 SX5
    ON X5_TABELA = '05'
    AND X5_FILIAL = E2_FILIAL
    AND X5_CHAVE = E2_TIPO
    AND SX5.D_E_L_E_T_ = ''
WHERE E2_VENCTO BETWEEN @DATAINI AND @DATAFIM
AND SE2.D_E_L_E_T_ = ''
GROUP BY DATEPART(MONTH, E2_VENCTO), DATEPART(YEAR, E2_VENCTO)

UNION ALL

SELECT 
    'Contas a Receber' AS Tipo,
    DATEPART(MONTH, E1_VENCTO) AS MES,
    DATEPART(YEAR, E1_VENCTO) AS Ano,
    FORMAT(COUNT(E1_NUM), '#,0.0000', 'pt-BR') AS QTDE,
    FORMAT(SUM(E1_SALDO), '#,0.0000', 'pt-BR') AS VALOR,
    NULL AS PESO_LIQUID,
    NULL AS PESO_BRUTO
FROM SE1010 SE1
INNER JOIN SX5010 SX5
    ON X5_TABELA = '05'
    AND X5_FILIAL = E1_FILIAL
    AND X5_CHAVE = E1_TIPO
    AND SX5.D_E_L_E_T_ = ''
WHERE E1_VENCTO BETWEEN @DATAINI AND @DATAFIM
AND SE1.D_E_L_E_T_ = ''
GROUP BY DATEPART(MONTH, E1_VENCTO), DATEPART(YEAR, E1_VENCTO)
ORDER BY Ano, MES, Tipo;
