SELECT 
	SDC.DC_FILIAL							AS FILIAL_EMPENHO, 
	SDC.DC_PRODUTO							AS COD_PROD_EMPENHADO,  
	SDC.DC_LOCALIZ							AS ACONDICIONAMENTO, 
	DC_QUANT								AS QUANTIDADE_EMPENHADA, 
	CAST(ZP4.ZP4_DATA AS DATE)				AS DATA_RESERVA,
	ZP4.ZP4_CODIGO							AS NUMERO_RESERVA_PORTAL,
	CASE
			WHEN ZP4.ZP4_STATUS = '1'
				THEN 'AGUARDANDO'
			WHEN ZP4.ZP4_STATUS = '2'
				THEN 'CONFIRMADA'
			WHEN ZP4.ZP4_STATUS = '3'
				THEN 'EXPIRADA'
			WHEN ZP4.ZP4_STATUS= '4'
				THEN 'CANCELADA'
			ELSE 'N/I'
	END										AS STATUS_RESERVA,
	ZP4.ZP4_CODCLI + '-' + ZP4.ZP4_LOJCLI	AS CODIGO_LOJA_CLIENTE,
	ISNULL(ZP6.ZP6_NUM,'NÃO')				AS PEDIDO_PORTAL,
	
	CASE
			WHEN ZP5.ZP5_NUM IS NULL
				THEN 'NÃO'
			ELSE 
				CASE
					WHEN ZP5.ZP5_STATUS = '0'
						THEN 'REVISÃO'
					WHEN ZP5.ZP5_STATUS = '1'
						THEN 'MANUTENÇÃO'
					WHEN ZP5.ZP5_STATUS = '2'
						THEN 'AGUARDANDO APROVAÇÃO'
					WHEN ZP5.ZP5_STATUS = '3'
						THEN 'EM APROVAÇÃO'
					WHEN ZP5.ZP5_STATUS = '4'
						THEN 'AGUARDANDO CONFIRMAÇÃO'
					WHEN ZP5.ZP5_STATUS = '5'
						THEN 'CONFIRMADO'
					WHEN ZP5.ZP5_STATUS = '6'
						THEN 'NÃO APROVADO'
					WHEN ZP5.ZP5_STATUS = '7'
						THEN 'CANCELADO'
					WHEN ZP5.ZP5_STATUS = '8'
						THEN 'APROVAÇÃO TECNICA'
					WHEN ZP5.ZP5_STATUS = '9'
						THEN 'AGUARDANDO PROCESSAMENTO'
					WHEN ZP5.ZP5_STATUS = 'A'
						THEN 'EM PROCESSAMENTO'
					WHEN ZP5.ZP5_STATUS = 'B'
						THEN 'ERRO PROCESSAMENTO'
				END
	END										AS STATUS_PEDIDO_PORTAL,
	
	
	ISNULL(SC6.C6_NUM, 'NÃO')				AS PEDIDO_INTERNO,
	CASE
		WHEN SC5.C5_NUM IS NULL
			THEN 'NÃO'
		ELSE
			CASE
				WHEN SC5.C5_LIBEROK = 'E' OR SC5.C5_NOTA <> '' OR SC6.C6_BLQ = 'R ' OR SC6.C6_QTDENT >= SC6.C6_QTDVEN
					THEN 'ENCER./CANC./BLOQ.'
				ELSE 'EM ABERTO'
			END											
	END										AS STATUS_PEDIDO_INTERNO

FROM SDC010 SDC WITH(NOLOCK)

LEFT JOIN ZP4010 ZP4 WITH(NOLOCK)
	ON SDC.DC_FILIAL  = ZP4.ZP4_FILIAL
	AND SDC.DC_PEDIDO = ZP4.ZP4_CODIGO
	AND SDC.D_E_L_E_T_ = ZP4.D_E_L_E_T_ 

LEFT JOIN ZP6010 ZP6 WITH(NOLOCK)
	ON  ZP6.ZP6_FILIAL IN ('','01','02')
	AND ZP4.ZP4_CODIGO = ZP6.ZP6_NUMRES
	AND ZP4.D_E_L_E_T_ = ZP6.D_E_L_E_T_

LEFT JOIN ZP5010 ZP5 WITH(NOLOCK)
	ON  ZP5.ZP5_FILIAL IN ('','01','02') 
	AND ZP6.ZP6_NUM = ZP5.ZP5_NUM
	AND ZP6.D_E_L_E_T_ = ZP5.D_E_L_E_T_

LEFT JOIN SC6010 SC6 WITH(NOLOCK)
	ON  SC6.C6_FILIAL IN ('','01','02')
	AND ZP6.ZP6_NUMRES = SC6.C6_ZZNRRES
	AND ZP6.D_E_L_E_T_ = SC6.D_E_L_E_T_

LEFT JOIN SC5010 SC5 WITH(NOLOCK)
	ON  SC6.C6_FILIAL	= SC5.C5_FILIAL
	AND SC6.C6_NUM		= SC5.C5_NUM
	AND SC6.D_E_L_E_T_  = SC5.D_E_L_E_T_


WHERE SDC.DC_ORIGEM = 'ZP4'
AND SDC.D_E_L_E_T_ <> '*'


-- ZP4_STATUS = '1' //STATUS PENDENTE
/*

SELECT *
--UPDATE ZP4010 SET ZP4_STATUS = '1'
FROM ZP4010
WHERE ZP4_FILIAL = '01'
AND ZP4_CODIGO = '001363'
AND D_E_L_E_T_ = ''
*/