-- ZP9 - Orcamento Itens Cores 
Select B1_XPORTAL,ZP9_NUM,ZP9_ITEM,B1_BOBINA,B1_ROLO,ZP9_TOTAL,ZP9_QUANT,B1_COD,B1_DESC,B1_XPORTAL,

	--Verifica Tipo de Acondicionamento 
	Case 
	When ZP6_ACOND = 'B' Then 'BOBINA'
	When ZP6_ACOND = 'R' Then 'ROLO'
	Else 'VERIFICAR'
	End AS ACONDICIONAMENTO,

	-- ANALISA METRAGEM BOBINA MÁXIMA ROLO OU BOBIBA
	Case 
	When ZP6_ACOND = 'B' and Isnull((NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)),'') > B1_BOBINA Then '*******ANALISAR METRAGEM MÁXIMA BOBINA*******'
	When ZP6_ACOND = 'R' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) > B1_ROLO Then '*******ANALISAR METRAGEM MÁXIMA ROLO*******'
	When ZP6_ACOND = 'B' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) <= B1_BOBINA Then 'METRAGEM MÁXIMA BOBINA VÁLIDA'
	When ZP6_ACOND = 'R' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) <= B1_ROLO Then 'METRAGEM MÁXIMA ROLO VÁLIDA'
	Else 'VERIFICAR'
	End AS Status_,

	-- ANALISA METRAGEM BOBINA MÁXIMA ROLO OU BOBIBA - Recomendações 
	Case 
	When ZP6_ACOND = 'B' and Isnull((NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)),'') > B1_BOBINA 
	Then '*******VERIFICAR CADASTRO PRODUTO BOBINA MÁXIMA ESTA CONFORME METRAGEM DO PV*******'
	When ZP6_ACOND = 'R' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) > B1_ROLO 
	Then '*******VERIFICAR CADASTRO PRODUTO ROLO MÁXIMA ESTA CONFORME METRAGEM DO PV*******'
	When ZP6_ACOND = 'B' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) <= B1_BOBINA 
	Then 'METRAGEM MÁXIMA NO CADASTRO DO PRODUTO ESTA DE ACORDO COM O PV'
	When ZP6_ACOND = 'R' and (NULLIF(ZP9_TOTAL,0)/NULLIF(ZP9_QUANT,0)) <= B1_ROLO 
	Then 'METRAGEM MÁXIMA ROLO VÁLIDA'
	Else 'VERIFICAR'
	End AS RECOMENDACAO,


* From ZP9010 ZP9

	Inner Join SB1010 SB1
	On B1_COD = ZP9_CODPRO
	And SB1.D_E_L_E_T_ = ''

	Inner Join ZP6010 ZP6
	On ZP6_NUM = ZP9_NUM
	And ZP6_ITEM = ZP9_ITEM
    And ZP6.D_E_L_E_T_ = ''

Where ZP9_NUM = '395086'
And ZP9.D_E_L_E_T_ =' '
Order By 2
--Tipos de Acondionamento 
--{B','BOBINA'}
--{'R','ROLO'}
--{'C','CARRETEL PLASTICO'}
--{'M','CARRETEL MADEIRA'}
--{'L','BLISTER'}
